### ISSUE TITLE
Finish effects stop working (updated with material of it happening)

### ISSUE THREAD

**Issue by lamperouqe** [tullamods/OmniCC#112]
Problem still persists with the new version that reset the settings. In this picture you can see that the finish effect is set to Activate and the finish effect on the defile icon is the default one.
![hqppmm8](https://cloud.githubusercontent.com/assets/9961187/5208816/60152a3a-75c0-11e4-8089-e72b56ea1685.png)
Works after reload but stops working after getting into combat, or works only sometimes. I even frapsed it happening for you here: https://www.youtube.com/watch?v=3aiLaNHSUW4

My addons:
Auctioneer
Auto Combat Logger
Bagnon
Bartender4
BasicMinimap
Big Wigs
Breeze
Broker: Cash_flow
Broker: Garrison
Chocolatebar
ClassTimer
Easymail 3.6
Elkano's Buff Bars
Garrison Mission Manager
Grid
GTFO
GuildCheck
HandyNotes
HandyNotes_DraenorTreasures
iMail
kgPanels
LittleWigs
Magic Runes
Mapster
Masque
Masque: Caith
Mik's Scrolling Battle Text
MoveAnything
OmniCC
Prat 3.0
Quartz
Repair Broker
SellJunk
Shadowed Unit Frames
SharedMedia
Skada
Skinner
SLDataText
SpamageMeters
TellMeWhen
TidyPlates
TidyPlates: Threat Plates
TimeToDie
TipTac
UnlimitedChatMessage
WhoWhisperedMe

**Comment by arcadepro** [comment]
Listing your addons isn't that helpful really. Test it without any other addons loaded.

**Comment by Jaliborc** [comment]
Also, the video is not available. O.o
