### ISSUE TITLE
OmniCC blocks creation of focus frame

### ISSUE THREAD

**Issue by ceylina** [tullamods/OmniCC#117]
When running for awhile and deciding to set focus to a player, I get the dreaded warning that blizzard has blocked an addon (OmniCC). Looks like some protected function or some other blizzard "thing" is being hit by OmniCC or most likely some other taint is causing some funky behavior. It only happens when I try and create a focus frame.

Now I have been switching between pitbull and shadowed unit frames so I am not sure if both of them are part of the problem but I do know one of the two had the option to disable omnicc from working with the unit frame.

when I do a UI reload it works again but this happens almost every time after entering a raid or dungeon instance and then trying to set focus after being in combat.

oh and of course no lua errors to detail what is happening. :(

**Comment by arcadepro** [comment]
Usually caused by something tainting DropDownMenu stuff.

**Comment by ceylina** [comment]
Yeah learned tons of how WoD reintroduced raid frame taint across the board. Seems it's getting better now and so long as no menu is touched in,around, through, or even looked at during combat

**Comment by Jaliborc** [comment]
Yeah, that is some random addon that uses UiDropMenu. OmniCC does use UIDropMenu, but only in the load on demand portion (for selecting the profile).
Hence, unless you have configured OmniCC in a given session, it is being randomly blamed.
