### ISSUE TITLE
Can ImniCC show countdown, not cooldown

### ISSUE THREAD

**Issue by Angelhearth** [tullamods/OmniCC#121]
I have a /castsequence macro that consists of 13 spells/abilities and I would like an overlay that shows how many times I've pressed the button the macro is attached to. ie. 13 before it's hit the first time, then 12-11-10...

Can OmniCC do this? If not, does anyone know of an addon that will do so?

**Comment by Jaliborc** [comment]
Its out of scope of what we intend with OmniCC. Sorry, I don't know of any mod that does it.
