### ISSUE TITLE
Bug, "OmniCC tried to call protected function"

### ISSUE THREAD

**Issue by Cursedcruiser** [tullamods/OmniCC#122]
Occurred right after I summoned my hunter pet during combat. Using Bartender4 and Adibuttonauras among other addons.

1x [ADDON_ACTION_BLOCKED] AddOn 'OmniCC' tried to call the protected function 'CompactRaidFrame2:SetAttribute()'.
!BugGrabber\BugGrabber.lua:589: in function <!BugGrabber\BugGrabber.lua:589>
[C]: in function `SetAttribute'
FrameXML\CompactUnitFrame.lua:134: in function`CompactUnitFrame_SetUnit'
...actRaidFrames\Blizzard_CompactRaidFrameContainer.lua:318: in function `CompactRaidFrameContainer_AddUnitFrame'
...actRaidFrames\Blizzard_CompactRaidFrameContainer.lua:272: in function`CompactRaidFrameContainer_AddPets'
...actRaidFrames\Blizzard_CompactRaidFrameContainer.lua:182: in function `CompactRaidFrameContainer_LayoutFrames'
...actRaidFrames\Blizzard_CompactRaidFrameContainer.lua:130: in function`CompactRaidFrameContainer_TryUpdate'
...actRaidFrames\Blizzard_CompactRaidFrameContainer.lua:62: in function `CompactRaidFrameContainer_OnEvent'
[string "_:OnEvent"]:1: in function <[string "_:OnEvent"]:1>

Locals:

**Comment by Stanzilla** [comment]
```
1x [ADDON_ACTION_BLOCKED] AddOn 'OmniCC' tried to call the protected function 'CompactRaidFrame3:Show()'.
!BugGrabber\BugGrabber.lua:589: in function <!BugGrabber\BugGrabber.lua:589>
[C]: in function `Show'
FrameXML\CompactUnitFrame.lua:290: in function `CompactUnitFrame_UpdateVisible'
FrameXML\CompactUnitFrame.lua:248: in function `CompactUnitFrame_UpdateAll'
FrameXML\CompactUnitFrame.lua:149: in function <FrameXML\CompactUnitFrame.lua:149>

Locals:
```

yup, same here.
