### ISSUE TITLE
CD's on buttons are no longer working 6.1 - for macro'd spells

### ISSUE THREAD

**Issue by vincentnl** [tullamods/OmniCC#125]
#showtooltip Shield Slam
/cast Berserker Rage
/cast Shield Slam

Used to show cooldown - but no longer, since 6.1

**Comment by Jaliborc** [comment]
Blizzard might have changed how to display cooldowns on macros. We only show text for existing cooldowns. Something was changed on Blizzard's end, not ours I believe.
