### ISSUE TITLE
GCD effect issue

### ISSUE THREAD

**Issue by Drunhyjal** [tullamods/OmniCC#126]
Hi, 

So i found out when something triggers a GCD spiral, like casting a spell, and you interrupt your cast BEFORE the end of the GCD spiral, then the final shining effect for GCD occurs and gets stuck onto the icons until the GCD gets triggered again.
Appeared after wow 6.1 release when i switched from 6.04 to 6.010. To switch back doesn't help, even deleting saved variables ( maybe could i have forgotten some files somewhere... ? )
I also tried 6.06, 6.07, 6.08, 6.09, same thing.

**Comment by Drunhyjal** [comment]
i tried to disable all my addons, and the bug still here oO 
it's just driving me crazy...

**Comment by 2ndHouse** [comment]
I've got the same problem, it even seems to be effecting frames other than my action bars. Decursive for example will also display this problem sometimes.

**Comment by 2ndHouse** [comment]
Drunhyjal, do you mean you disabled OmniCC too? If so, then it most be a current Blizzard bug?

**Comment by Drunhyjal** [comment]
Yes i disabled OmniCC.
And i thought it was a blizzard bug too, but i don't know...

**Comment by Jaliborc** [comment]
That sounds like a blizz problem
