### ISSUE TITLE
Better GCD handling

### ISSUE THREAD

**Issue by Stanzilla** [tullamods/OmniCC#128]
I was recently told that there now is a spell in the game that is made for GCD checking. It is spell ID 61304 and works for all classes, which is amazing. 

Now we could have a setting to ignore the Global Cooldown when showing cooldowns on buttons.
Also I would like to request that the stepping of the "Minimum duration to display text" slider be changed to 0.x second steps so you can have it show cooldowns with 1.3s duration for example.

**Comment by Stanzilla** [comment]
@Jaliborc poke!

**Comment by Stanzilla** [comment]
@Jaliborc poke!

**Comment by Jaliborc** [comment]
Cool! This is amazing! Thank you for the pokes, or I might have missed it.

**Comment by Stanzilla** [comment]
yay, thank you!
