### ISSUE TITLE
Support with Elvui / Buffs & Debuffs

### ISSUE THREAD

**Issue by lanc3lot** [tullamods/OmniCC#130]
![example-buffselvuiomni](https://cloud.githubusercontent.com/assets/12452171/7643672/2d3ab29c-faa4-11e4-8f99-c94faa8c091a.jpg)

I dont know if the problem appear only on me, the issue i have is that i use Elvui with Omnicc. I have disabled Elvui to show any cooldowns and also wow itself. Although in my Actionbars everything is ok, in my Buffs / Debuffs position, where all my buffs and debuffs appear through Elvui, it shows only a bar below the buff / debuff and not the exact number. And ok, in the example picture i have only Bloodlust as debuff and its not so important, but in a real fight, i would like with a quick glance to be able to see what's my debuff timer exactly. 

Hope you understand what i mean, and you can help me solve it :)

**Comment by Jaliborc** [comment]
Those buffs don't have a cooldown spiral. Thats what OmniCC uses to detect "cooldowns". As such, they are not technically cooldowns, but timer bars, and OmniCC cannot do anything about it.

**Comment by lanc3lot** [comment]
I see, pity that cant be covered by Omnicc, do u have any knowledge of an addon that can cover that one? So i can have timers for my debuffs?

**Comment by lanc3lot** [comment]
Nvm, i have found Phalanxbuffs for anyone need something like that. Keep up the good work guys :)
