### ISSUE TITLE
text recovery

### ISSUE THREAD

**Issue by zooloogorbonos** [tullamods/OmniCC#131]
http://imagizer.imageshack.com/img538/3207/YxrXUL.jpg

If the button for more than two timers recovery, they do not display correctly overlapped.

**Comment by Jaliborc** [comment]
I don't understand what you mean. What is a two timers recovery? When a spell has multiple charges? Also, does this also happens in the action bar?

Are you using any action bar mods?

**Comment by trigunflame** [comment]
Yes, that is what he means. As a mage for example, Supernova or Ice Nova will replicate this bug. I'm using dominos as my action bar fyi. 

I've resorted to just using blizzards default cooldown text until you find a way and/or decide to fix it.
