### ISSUE TITLE
Additional Charge Timer not showing

### ISSUE THREAD

**Issue by TangyTooTall101** [tullamods/OmniCC#132]
Since 6.2 patch, the timer for gaining additional charges on things like Starsurge or Starfall isn't showing unless all the charges are gone.

Going from 0->1 charge, the timer shows just fine. Going from 1->2, 2->3, nothing shows.

**Comment by Jaliborc** [comment]
Have you checked which is your charging alpha setting? If it is 0, then the charges won't appear.

**Comment by TangyTooTall101** [comment]
It was an issue with bartender needing to be updated.
