### ISSUE TITLE
Double Cooldown text

### ISSUE THREAD

**Issue by reaper666735** [tullamods/OmniCC#137]
Hello , 

Recently i have been randomly seeing double the Cooldown numbers counting down behind one another ( besides the Charge based spells ) on different characters , i have no idea if it's Blizzards own Cooldown numbers being shown even if the option is Greyed out ( and not checked ) while using OmniCC ...... ,  or somehow since latest patch the addon being " confused " and showing it 2 times lol ..... , really dunno how to explain it otherwise  :( 

i hope you can find out what it possible can be , seems on Curse.com OmniCC page are comments with similar problems aswell  ......

good day.

**Comment by fableman** [comment]
yeah, happens to me as well. it's like either the native CD timer is being shown and overlapped with the one from Omni or both from Omni.

**Comment by Stertuos** [comment]
It appears to have something to do with the "Restoring Charges" option under Text Style. I was increasing the size of it while the two numbers were showing and one of them was reacting to it. 

No idea how to fix, just thought that it may help~

**Comment by reaper666735** [comment]
found this picture of the issue on Curse.com page from another user so you can better see it in action.
![omnicc bug](https://cloud.githubusercontent.com/assets/5812860/11809740/43cdb4e0-a329-11e5-8951-1b2fad5c911c.png)
