### ISSUE TITLE
UpdateText nil error

### ISSUE THREAD

**Issue by ceylina** [tullamods/OmniCC#138]
Using Version 6.2 and establishing a group and rule to disable cooldown text in unit frames (so they can handle it themselves and not through omnicc), this happens if a cooldown was about to expire before reloading the UI after setting the rule

Strange thing and this could be some Blizzard shenanigans, a lot of addons that are using GetTime() are getting nil errors lately post 10/21/2015 hotfix

OmniCC\core\timer.lua:90: attempt to compare number with nil
OmniCC\core\timer.lua:90: in function `UpdateText'
OmniCC\engines\animation-Animation.lua:65: in function`OnFinished'
OmniCC\engines\animation-Animation.lua:26: in function <OmniCC\engines\animation.lua:25>

Locals:
self = <unnamed> {
 group = <unnamed> {
 }
 frame = <unnamed> {
 }
 0 = <userdata>
 animation = <unnamed> {
 }
}

**Comment by Jaliborc** [comment]
Still present on 7.x versions?

**Comment by Jaliborc** [comment]
Believe I just hotfixed it in 7.1
