### ISSUE TITLE
Recharge disapears after gaining a charge

### ISSUE THREAD

**Issue by narils** [tullamods/OmniCC#142]
If Dark soul gains a goes from 0 to 1 stacks the recharge text doesn't show.
if it's at 2 charges and you use one, it will show rechargetimer at 1 charge, but not if it goes from 0 charges to 1.

> Haven't tested other spells, but should probably be true for deterrence as well.

Tested other recharge spells, only applies to Dark soul

**Comment by lolo1337** [comment]
Something similiar is happening with PW: Radiance. it is super annoying
