### ISSUE TITLE
OmniCC and IceHUD Totem frames

### ISSUE THREAD

**Issue by ceylina** [tullamods/OmniCC#144]
I'm editing this because the first draft was not clear...

IceHUD, a popular HUD addon has an option to display icons (button frames) for active totems from shaman. Attached is an example of these with timers disabled.

![totes](https://cloud.githubusercontent.com/assets/9342192/13556396/1503f484-e39e-11e5-9ad7-d432da7c4aa2.jpg)

In the Default group if I set the "minimum size to display text" to a certain number it shows on these icons. For example, setting them to 80 shows on the size I have them scaled to in IceHUD.

In order to have them show at a readable size, I need to disable "automatically scale text to fit within frames". Doing so allows me to have a readable cooldown text.

The issue is I need to also scale the under a minute slider to around 135% to make them readable. This of course scales everything that utilizes the default group. that's not optimal for my tastes.

I attempted to make a new group so that I could scale this text on IceHUD to work. The issue is regardless of how I create it (tried making the group IceHUD, the totem frame name of "IceHUD_Totems", making a rule for IceHUD_Totems, etc). No matter what I have tried, it will not overrule the default group. I have tried setting the minimum size slider to a number larger than what the icehud totems will be (82 for example) but it does nothing.

So this is why I edited this report...

Based on this issue report, 

https://github.com/tullamods/OmniCC/issues/141

I noticed that IceHUD is using 

self.frame.graphical[totem].cd:SetCooldown(startTime, duration)

For cooldown timers. Switching to 

CooldownFrame_SetTimer(self.frame.graphical[totem].cd, startTime, duration, true)

Completely changed the way it drew the timer text.

Now it still doesn't let me create a group for this frame but it does allow me to scale the text in a much better way and use the automatically scale checkbox in the settings without it shrinking to an unreadable size.

![wowscrnshot_030616_140215](https://cloud.githubusercontent.com/assets/9342192/13556620/270ea236-e3a4-11e5-9a77-27a7a36732af.jpg)

**Comment by Tuller** [comment]
IceHUD should be matched a bit better in the beta. There's also no rendering differences now.
