### ISSUE TITLE
Icon Text CD change

### ISSUE THREAD

**Issue by Orumage** [tullamods/OmniCC#145]
Hi, in the old version when a skill was coming down on cd put "3m" and now you put it "3min" and I do not like, is there any option to change settings addon or must be changed manually?

**Comment by zooloogorbonos** [comment]
Furiously I agree! Old version was much better! If he did not I would have long switched to the standard. On the Russian forum Blizzard a lot of people who also did not like it. Huge please return the old varint or at least make the inclusion of the old varinta settings. Thanks in advance

**Comment by Jaliborc** [comment]
I didn't realized some locales had inproper translations of %m. I'll revert back to OmniCC localizations next version.
