### ISSUE TITLE
MM:SS format displays as literally "Minimum duration to display text as MM:SS"

### ISSUE THREAD

**Issue by Vusys** [tullamods/OmniCC#148]
Updated to 6.2.4 and now MM:SS displays like this:

![wowscrnshot_060116_213325](https://cloud.githubusercontent.com/assets/4213522/15725178/841c45d6-2842-11e6-98dc-bfd5d3b0d2fd.jpg)

The cooldown on Crystal is about 2 minutes in that screenshot.

**Comment by Jaliborc** [comment]
Duplicate. Fixed
