### ISSUE TITLE
Debuffs' cooldowns are in the 'charging' group

### ISSUE THREAD

**Issue by warbaby** [tullamods/OmniCC#153]
This is why some cc font size is too small.

OmniCC/core/timer.lua:42

self.charging = self.cooldown:GetDrawEdge()

better change to :

self.charging = not self.cooldown:GetDrawSwipe()

**Comment by daindark** [comment]
this is working, can we add this on the release?

**Comment by Solor** [comment]
come across this bug since BfA, only happens with ouf unitframe's aura
@warbaby 's solution works

![wowscrnshot_080618_152435](https://user-images.githubusercontent.com/156806/43702873-b627cdac-998d-11e8-8826-4433d00e2764.png)

**Comment by Tuller** [comment]
This is the rule i'm using in the betas to determine if the cooldown is a charge one or not. It works for standard actions + libactionbutton buttons at the very least.
```lua
local parent = cooldown:GetParent()
if parent and parent.chargeCooldown == cooldown then
    return "charge"
end
```
