### ISSUE TITLE
Lua error

### ISSUE THREAD

**Issue by viola15** [tullamods/OmniCC#157]
I have this alert showing every time I log in:

Message: Interface\AddOns\OmniCC\effects\alert.lua:30: attempt to call method 'SetChange' (a nil value)
Time: 08/20/16 07:57:18
Count: 1
Stack: Interface\AddOns\OmniCC\effects\alert.lua:30: in function `newAnim'
Interface\AddOns\OmniCC\effects\alert.lua:35: in main chunk

Locals: type = "Alpha"
change = 0.7
order = 1
anim = <unnamed> {
 0 = <userdata>
}
(_temporary) = nil
(_temporary) = <unnamed> {
 0 = <userdata>
}
(_temporary) = 0.7
(_temporary) = "attempt to call method 'SetChange' (a nil value)"
Anims = <unnamed> {
 0 = <userdata>
}

**Comment by Jaliborc** [comment]
It appears you are running OmniCC on an older version of WoW. We do not support private servers, but you can use an older version of OmniCC.

**Comment by viola15** [comment]
This is happening on live for me when I log in garrison, I am not running an older version of wow I am playing the live version of it. Is there any other reason that could be happening?

**Comment by Jaliborc** [comment]
Not the latest version, double checked
