### ISSUE TITLE
Lua Error, Interaction with BigDebuffs

### ISSUE THREAD

**Issue by bullsei** [tullamods/OmniCC#170]
Using the latest version of this addon and BigDebuffs. 
Lua Errors:
```
3x OmniCC\core\timer.lua:99: attempt to compare number with nil
OmniCC\core\timer.lua:99: in function `UpdateText'
OmniCC\core\timer.lua:165: in function `UpdateShown'
OmniCC\core\timer.lua:56: in function `Start'
OmniCC\core\cooldown.lua:16: in function <OmniCC\core\cooldown.lua:11>
[C]: in function `SetCooldown'
BigDebuffs\BigDebuffs-v5.1.lua:1083: in function <BigDebuffs\BigDebuffs.lua:1057>
BigDebuffs\BigDebuffs-v5.1.lua:1284: in function <BigDebuffs\BigDebuffs.lua:1203>
[C]: in function `CompactUnitFrame_UpdateDebuffs'
FrameXML\CompactUnitFrame.lua:535: in function `CompactUnitFrame_UpdateAuras'
FrameXML\CompactUnitFrame.lua:95: in function <FrameXML\CompactUnitFrame.lua:51>

Locals:
self = <unnamed> {
 0 = <userdata>
 abRatio = 0.61111111111111
 text = <unnamed> {
 }
 finish = 363369.741
 charging = false
 cooldown = CompactRaidFrame1Debuff1Cooldown {
 }
 controlled = false
}
forceStyleUpdate = nil
(*temporary) = nil
(*temporary) = 363369.741
(*temporary) = 363369.741
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to compare number with nil"
GetTime = <function> defined =[C]:-1
OmniCC = OmniCC {
 0 = <userdata>
 UpdateGroups = <function> defined @OmniCC\settings\groups.lua:81
 Cache = <table> {
 }
 SetupEvents = <function> defined @OmniCC\main.lua:43
 FindGroup = <function> defined @OmniCC\settings\groups.lua:30
 GetGroupIndex = <function> defined @OmniCC\settings\groups.lua:49
 VARIABLES_LOADED = <function> defined @OmniCC\main.lua:25
 GetGroupSettingsFor = <function> defined @OmniCC\settings\groups.lua:11
 New = <function> defined @OmniCC\main.lua:96
 GetUpdateEngine = <function> defined @OmniCC\effects\effects.lua:48
 Meta = <table> {
 }
 GetEffect = <function> defined @OmniCC\effects\effects.lua:24
 UpgradeSettings = <function> defined @OmniCC\settings\settings.lua:37
 AddGroup = <function> defined @OmniCC\settings\groups.lua:60
 AniUpdater = <unnamed> {
 }
 RemoveGroup = <function> defined @OmniCC\settings\groups.lua:70
 SetupCommands = <function> defined @OmniCC\main.lua:69
 Cooldown = <unnamed> {
 }
 StartupSettings = <function> defined @OmniCC\settings\settings.lua:20
 GetGroupSettings = <function> defined @OmniCC\settings\groups.lua:16
 GetVersion = <function> defined @OmniCC\settings\settings.lua:98
 GetGroup = <function> defined @OmniCC\settings\groups.lua:20
 StartupGroup = <function> defined @OmniCC\settings\settings.lua:49
 Actions = <table> {
 }
 ScriptUpdater = <unnamed> {
 }
 TriggerEffect = <function> defined @Ace3\AceHook-3.0\AceHook-3.0.lua:100
 SetupConfig = <function> defined @OmniCC\main.lua:49
 sets = <table> {
 }
 effects = <table> {
 }
 GetButtonIcon = <function> defined @OmniCC\effects\effects.lua:31
 RegisterEffect = <function> defined @OmniCC\effects\effects.lua:19
 Startup = <function> defined @OmniCC\main.lua:13
 SetupEffect = <function> defined @OmniCC\effects\effects.lua:14
 Timer = <unnamed> {
 }
 PLAYER_ENTERING_WORLD = <function> defined @OmniCC\main.lua:89
 ACTIONBAR_UPDATE_COOLDOWN = <function> defined @OmniCC\main.lua:85
 SetupHooks = <function> defined @OmniCC\main.lua:35
```

**Comment by Jaliborc** [comment]
Ok, hotfixed

**Comment by bullsei** [comment]
i know you closid this, but i still got a related? error today.

`1x OmniCC\core\timer.lua:125: attempt to compare number with nil
OmniCC\core\timer.lua:125: in function `UpdateText'
OmniCC\core\timer.lua:165: in function `UpdateShown'
OmniCC\core\timer.lua:56: in function `Start'
OmniCC\core\cooldown.lua:16: in function <OmniCC\core\cooldown.lua:11>
[C]: in function `SetCooldown'
BigDebuffs\BigDebuffs-v5.2.lua:1077: in function <BigDebuffs\BigDebuffs.lua:1051>
BigDebuffs\BigDebuffs-v5.2.lua:1278: in function <BigDebuffs\BigDebuffs.lua:1197>
[C]: in function `CompactUnitFrame_UpdateDebuffs'
FrameXML\CompactUnitFrame.lua:535: in function `CompactUnitFrame_UpdateAuras'
FrameXML\CompactUnitFrame.lua:95: in function <FrameXML\CompactUnitFrame.lua:51>

Locals:
self = <unnamed> {
 0 = <userdata>
 abRatio = 0.61111111111111
 text = <unnamed> {
 }
 finish = 17969.06
 charging = false
 cooldown = CompactRaidFrame2Debuff1Cooldown {
 }
 controlled = false
}
forceStyleUpdate = nil
remain = 0
(*temporary) = nil
(*temporary) = 30.000000447035
(*temporary) = OmniCC {
 0 = <userdata>
 UpdateGroups = <function> defined @OmniCC\settings\groups.lua:81
 Cache = <table> {
 }
 SetupEvents = <function> defined @OmniCC\main.lua:43
 FindGroup = <function> defined @OmniCC\settings\groups.lua:30
 GetGroupIndex = <function> defined @OmniCC\settings\groups.lua:49
 VARIABLES_LOADED = <function> defined @OmniCC\main.lua:25
 GetGroupSettingsFor = <function> defined @OmniCC\settings\groups.lua:11
 New = <function> defined @OmniCC\main.lua:96
 GetUpdateEngine = <function> defined @OmniCC\effects\effects.lua:48
 Meta = <table> {
 }
 GetEffect = <function> defined @OmniCC\effects\effects.lua:24
 UpgradeSettings = <function> defined @OmniCC\settings\settings.lua:37
 AddGroup = <function> defined @OmniCC\settings\groups.lua:60
 AniUpdater = <unnamed> {
 }
 RemoveGroup = <function> defined @OmniCC\settings\groups.lua:70
 SetupCommands = <function> defined @OmniCC\main.lua:69
 Cooldown = <unnamed> {
 }
 StartupSettings = <function> defined @OmniCC\settings\settings.lua:20
 GetGroupSettings = <function> defined @OmniCC\settings\groups.lua:16
 GetVersion = <function> defined @OmniCC\settings\settings.lua:98
 GetGroup = <function> defined @OmniCC\settings\groups.lua:20
 StartupGroup = <function> defined @OmniCC\settings\settings.lua:49
 Actions = <table> {
 }
 ScriptUpdater = <unnamed> {
 }
 TriggerEffect = <function> defined @Ace3\AceHook-3.0\AceHook-3.0.lua:100
 SetupConfig = <function> defined @OmniCC\main.lua:49
 sets = <table> {
 }
 effects = <table> {
 }
 GetButtonIcon = <function> defined @OmniCC\effects\effects.lua:31
 RegisterEffect = <function> defined @OmniCC\effects\effects.lua:19
 Startup = <function> defined @OmniCC\main.lua:13
 SetupEffect = <function> defined @OmniCC\effects\effects.lua:14
 Timer = <unnamed> {
 }
 PLAYER_ENTERING_WORLD = <function> defined @OmniCC\main.lua:89
 ACTIONBAR_UPDATE_COOLDOWN = <function> defined @OmniCC\main.lua:85
 SetupHooks = <function> defined @OmniCC\main.lua:35
}
(*temporary) = "base"
(*temporary) = <table> {
 minDuration = 2.0000000298023
 styles = <table> {
 }
 tenthsDuration = 0
 minSize = 0.5
 minEffectDuration = 30.000000447035
 mmSSDuration = 0
 spiralOpacity = 1.0099999774247
}
(*temporary) = <function> defined @OmniCC\settings\groups.lua:16
(*temporary) = OmniCC {
 0 = <userdata>
 UpdateGroups = <function> defined @OmniCC\settings\groups.lua:81
 Cache = <table> {
 }
 SetupEvents = <function> defined @OmniCC\main.lua:43
 FindGroup = <function> defined @OmniCC\settings\groups.lua:30
 GetGroupIndex = <function> defined @OmniCC\settings\groups.lua:49
 VARIABLES_LOADED = <function> defined @OmniCC\main.lua:25
 GetGroupSettingsFor = <function> defined @OmniCC\settings\groups.lua:11
 New = <function> defined @OmniCC\main.lua:96
 GetUpdateEngine = <function> defined @OmniCC\effects\effects.lua:48
 Meta = <table> {
 }
 GetEffect = <function> defined @OmniCC\effects\effects.lua:24
 UpgradeSettings = <function> defined @OmniCC\settings\settings.lua:37
 AddGroup = <function> defined @OmniCC\settings\groups.lua:60
 AniUpdater = <unnamed> {
 }
 RemoveGroup = <function> defined @OmniCC\settings\groups.lu`
