### ISSUE TITLE
AddOn 'OmniCC' tried to call the protected function 'CompactRaidFrame7:Show()'.

### ISSUE THREAD

**Issue by godsentdeath** [tullamods/OmniCC#181]
1x [ADDON_ACTION_BLOCKED] AddOn 'OmniCC' tried to call the protected function 'CompactRaidFrame7:Show()'.
!BugGrabber\BugGrabber.lua:573: in function <!BugGrabber\BugGrabber.lua:573>
[C]: in function `Show'
FrameXML\CompactUnitFrame.lua:339: in function `CompactUnitFrame_UpdateVisible'
FrameXML\CompactUnitFrame.lua:280: in function `CompactUnitFrame_UpdateAll'
FrameXML\CompactUnitFrame.lua:180: in function <FrameXML\CompactUnitFrame.lua:180>

**Comment by ceylina** [comment]
https://github.com/tullamods/OmniCC/issues/184#issuecomment-306382809
