### ISSUE TITLE
Error in 7.2

### ISSUE THREAD

**Issue by HnyBear** [tullamods/OmniCC#184]
Date: 2017-04-14 04:33:24
ID: 4
Error occured in: AddOn: OmniCC
Count: 5
Message: Note: AddOn OmniCC attempted to call a protected function (CompactRaidFrame1:ClearAllPoints()) during combat lockdown.
Debug:
   [C]: ClearAllPoints()
   ..\FrameXML\FlowContainer.lua:157: FlowContainer_DoLayout()
   ..\FrameXML\FlowContainer.lua:17: FlowContainer_ResumeUpdates()
   ...actRaidFrames\Blizzard_CompactRaidFrameContainer.lua:185: CompactRaidFrameContainer_LayoutFrames()
   ...actRaidFrames\Blizzard_CompactRaidFrameContainer.lua:130: CompactRaidFrameContainer_TryUpdate()
   ...actRaidFrames\Blizzard_CompactRaidFrameContainer.lua:62: CompactRaidFrameContainer_OnEvent()
   [string "*:OnEvent"]:1:
      [string "*:OnEvent"]:1

**Comment by ceylina** [comment]
The problem has nothing to do with omnicc and everything to do with using a custom raid frame addon and not disabling the necessary blizzard addons.

This addon or the script on the addon page should solve your problem if you use a custom raid frame addon like grid, pitbull, shadowed unit frames, or ElvUI

https://mods.curse.com/addons/wow/hideraidframe
