### ISSUE TITLE
Are you not Updating this addon anymore?

### ISSUE THREAD

**Issue by PoisonsGaming** [tullamods/OmniCC#185]
last update was 7.1 so like December or so anyways in 7.2 the addon is causing taint when attempting to join a random battleground
" 2x [ADDON_ACTION_FORBIDDEN] AddOn 'OmniCC' tried to call the protected function 'JoinBattlefield()'.
!BugGrabber\BugGrabber.lua:573: in function <!BugGrabber\BugGrabber.lua:573>
[C]: in function `JoinBattlefield'
Blizzard_PVPUI\Blizzard_PVPUI-1.0.lua:600: in function `HonorFrame_Queue'
[string "*:OnClick"]:2: in function <[string "*:OnClick"]:1>

Locals:
nil "

**Comment by Jaliborc** [comment]
See issue https://github.com/tullamods/OmniCC/issues/184
