### ISSUE TITLE
7.2 Error 06/10/2017

### ISSUE THREAD

**Issue by the2pit** [tullamods/OmniCC#187]
Date: 2017-06-10 09:13:24
ID: 1
Error occured in: AddOn: OmniCC
Count: 19
Message: Note: AddOn OmniCC attempted to call a protected function (CompactPartyFrameMember1:Show()) during combat lockdown.
Debug:
   [C]: Show()
   ..\FrameXML\CompactUnitFrame.lua:339: CompactUnitFrame_UpdateVisible()
   ..\FrameXML\CompactUnitFrame.lua:280: CompactUnitFrame_UpdateAll()
   ..\FrameXML\CompactUnitFrame.lua:54:
      ..\FrameXML\CompactUnitFrame.lua:51
Locals:
None

This keeps coming up more an more. PLEASE fix. love the addon and been using it for many years.

**Comment by Jaliborc** [comment]
See issue https://github.com/tullamods/OmniCC/issues/184
