### ISSUE TITLE
OmniCC Size

### ISSUE THREAD

**Issue by Nahox** [tullamods/OmniCC#189]
Hey,
 
I got a Problem that if you Target someone and Dot/Hot him the Timer Display (The Number in the Frame of the Dot/Hot) is way to small/tiny compared to the Timer Display from WoD/MoP. The Problem is if i change the Size of the Timer Display everything else gets messed up so i would be really appreciate if the Creator please could somehow fix it here are some screenshots:
 
Back in the Day it looked like this: 
https://gyazo.com/857f8b38ad8c87af146141b9bc7f3a4f
and now it looks like this: 
https://gyazo.com/576e42b3f257a75233915e1d98829713

Thank you!

**Comment by Jaliborc** [comment]
You can use the groups feature to control timers sizes separately on different cooldonws.
