### ISSUE TITLE
Text Shadow 

### ISSUE THREAD

**Issue by 1ps3** [tullamods/OmniCC#195]
A option to toggle text shadow would be pretty sweet, and maybe adjusting the offset. Though just regular (1,-1) offset would be pretty nice.

**Comment by Tuller** [comment]
Implemented in 8.3.0
![image](https://user-images.githubusercontent.com/191239/68535126-12190100-0335-11ea-8d9c-bd161a87194e.png)

**Comment by 1ps3** [comment]
Yo, thank the lord. I don't have to just keep my own branch <3

**Comment by 1ps3** [comment]
I'm pretty sure I just had some silly jank way or doing it anyway, plus I didn't really know where to put the option in the first place. When are you planning on uploading the changes?

**Comment by Tuller** [comment]
Its in the current beta on curse.

**Comment by 1ps3** [comment]
Just had a chance to test out the latest beta, it seems as though the option for vertial text shadow is the wrong way around. Unless it was intentional setting a positive value moves the shadow in a negative direction.

**Comment by Tuller** [comment]
Its intentional. Moving the slider right felt a bit better as a down than moving it left to me.
