### ISSUE TITLE
Keeps on bugging

### ISSUE THREAD

**Issue by Ezzey** [tullamods/OmniCC#197]
1x [ADDON_ACTION_FORBIDDEN] AddOn 'OmniCC' tried to call the protected function 'JoinBattlefield()'.
!BugGrabber\BugGrabber.lua:573: in function <!BugGrabber\BugGrabber.lua:573>
[C]: in function `JoinBattlefield'
Blizzard_PVPUI\Blizzard_PVPUI-1.0.lua:611: in function `HonorFrame_Queue'
[string "*:OnClick"]:2: in function <[string "*:OnClick"]:1>

Locals:
nil

**Comment by dstruct2k** [comment]
Also having this issue, but I can't seem to track down *what* is causing OmniCC to even hook into that frame?
