### ISSUE TITLE
Can't go to BG's

### ISSUE THREAD

**Issue by Askanon** [tullamods/OmniCC#199]
Everytime i trty to queue to battlegrounds, OmniCC throw an error

5x [ADDON_ACTION_FORBIDDEN] AddOn 'OmniCC' hat versucht die geschützte Funktion 'JoinBattlefield()' aufzurufen.
!BugGrabber\BugGrabber.lua:573: in function <!BugGrabber\BugGrabber.lua:573>
[C]: in function `JoinBattlefield'
Blizzard_PVPUI\Blizzard_PVPUI-1.0.lua:611: in function `HonorFrame_Queue'
[string "*:OnClick"]:2: in function <[string "*:OnClick"]:1>

Locals:
nil

**Comment by hungry** [comment]
Same here
