### ISSUE TITLE
Can't use Innkeeper's Daughter

### ISSUE THREAD

**Issue by Jaladhjin** [tullamods/OmniCC#209]
1x [ADDON_ACTION_FORBIDDEN] AddOn 'OmniCC_Config' tried to call the protected function 'UseToy()'.
!BugGrabber\BugGrabber.lua:573: in function <!BugGrabber\BugGrabber.lua:573>
[C]: in function `UseToy'
...faceBlizzard_Collections\Blizzard_ToyBox.lua:145: in function `ToySpellButton_OnClick'
[string "*:OnClick"]:4: in function <[string "*:OnClick"]:1>

Locals:
nil

**Comment by Jaliborc** [comment]
You pervert
