### ISSUE TITLE
/OmniCC/settings/groups-Groups.lua:31: Atemmpt to access forbidden object from code tainted by an AddOn

### ISSUE THREAD

**Issue by Kikky2z** [tullamods/OmniCC#211]

**Comment by nechapemnic** [comment]
1x [ADDON_ACTION_BLOCKED] AddOn 'OmniCC' tried to call the protected function 'CompactRaidFrame30:Show()'.
!BugGrabber\BugGrabber.lua:573: in function <!BugGrabber\BugGrabber.lua:573>
[C]: in function `Show'
FrameXML\CompactUnitFrame.lua:350: in function `CompactUnitFrame_UpdateVisible'
FrameXML\CompactUnitFrame.lua:283: in function `CompactUnitFrame_UpdateAll'
FrameXML\CompactUnitFrame.lua:117: in function <FrameXML\CompactUnitFrame.lua:53>

Locals:
InCombatSkipped
