### ISSUE TITLE
Doesn't work with frame:SetCooldownDuration()

### ISSUE THREAD

**Issue by wardz** [tullamods/OmniCC#214]
OmniCC does not currently update timer text when using `:SetCooldownDuration()`. Would be nice to have support for it if possible as it's more performant than `SetCooldown()` for refreshing active cooldowns.

**Comment by Tuller** [comment]
Do you have examples of using this? The only places I've seen it used on Blizzard's end is cooldown:SetCooldownDuration(0)

**Comment by wardz** [comment]
It's basically just doing e.g `cooldown:SetCooldownDuration(26)` versus `cooldown:SetCooldown(GetTime(), 26)` for a cooldown that is **already active**. 
I've never seen Blizzard use this except the one you mentioned, but I have seen it used in other addons. I don't recall which ones though and it is a very rare occurance.

**Comment by Tuller** [comment]
This should be easy enough for me to work with

**Comment by Tuller** [comment]
This should be implemented in beta3
