### ISSUE TITLE
OmniCC 8.0.0 breaks the new Honor Level overview

### ISSUE THREAD

**Issue by MisterUIltimo** [tullamods/OmniCC#215]
Here how it should look like: https://i.imgur.com/6iCL62P.jpg
And thats how it looks with OmniCC enabled: https://i.imgur.com/9vs42fW.jpg

The red bar is gone and as soon i open the player vs. player tab there is a 2 second timer. Then nothing.
Tested with only OmniCC enabled / disabled. No Lua error.

**Comment by Tuller** [comment]
Interesting, they use a cooldown object as a hack to show a percentage there.

**Comment by Tuller** [comment]
Can you test against the latest tullaCC version? I just applied a quick fix there:
https://www.wowinterface.com/downloads/info17602-tullaCooldownCount.html

**Comment by MisterUIltimo** [comment]
tullaCC is working. Using tullaCC now. Thanks for the fix.

**Comment by Soreox** [comment]
@Tuller Hi, I see this has been Closed but will there be a fix for OmniCC? 

local hideNumbers = {
		-- _G.PVPQueueFrame.HonorInset.HonorLevelDisplay
	}

Is there anyway to add this to OmniCC too?

Thanks:)

**Comment by Tuller** [comment]
It will but that’s not the implementation I actually used in tullaCC.
  

  
  

  
  
>

**Comment by Tuller** [comment]
This is fixed in the new version.
