### ISSUE TITLE
Honor Tab Bug

### ISSUE THREAD

**Issue by Akalia4** [tullamods/OmniCC#218]
I noticed that my honor tab had some weird bug where the round progress bar would turn black instead of orange and a timer would count down on it.

Tried turning off all addons and turning each on individually to identify that this issue was being cause by OmniCC

I'll provide a screenshot below to better show the issue.
https://imgur.com/AMfSohf

Would like to know if this is a known bug / if it is going to be addressed.

Thanks

**Comment by Tuller** [comment]
I believe this is fixed with the 8.0.1 version.

**Comment by Zalcore** [comment]
I can confirm this is  NOT fixed with the 8.0.1 version. :(

**Comment by Tuller** [comment]
That was my suspicion

**Comment by niord23** [comment]
Same problem here, its a weird bug. Can this be fixed? =)

**Comment by andreiunuchak** [comment]
Was fine in 8.0.5, but bug appeared again in 8.0.6
