### ISSUE TITLE
paper doll frame?

### ISSUE THREAD

**Issue by pacanukeha** [tullamods/OmniCC#223]
I'm using groups to turn off omnicc in Weak Auras but I'm having problems turning on items in the character viewer. I've tried adding a rule for:
PaperDollFrame
PaperDollItemsFrame
CharacterFrame
CharacterModelFrame
and none of them work.  Do you know the name of a frame I can enable that will work there?

**Comment by Tuller** [comment]
I think you want just Character as the rule
