### ISSUE TITLE
Is it Possible to make OmniCC only work for particular Groups of WA

### ISSUE THREAD

**Issue by ReeceClifford97** [tullamods/OmniCC#225]
Hi, Wondering if it is possible for OmniCC to only use the enable the cool down text for particular WeakAuras and exclude the functionality for different Weak Aura Groups

**Comment by Tuller** [comment]
I don't think WeakAura names things distinctly enough for that. I'm thinking about making the rules engine a bit more robust so that these things can be handled a bit better.
