### ISSUE TITLE
Elvui Nameplates BUG

### ISSUE THREAD

**Issue by Fatso5** [tullamods/OmniCC#226]
I would love to use only OMNICC to show the cooldown text on my elvui nameplates,but OmniCC is not showing always the cooldown text.Not only that,but it seems like its working randomly,because sometimes ( Even for example if i say that i only want to show a cooldown on an icon bigger then 120 , so i want OMNICC disabled for elvui nameplates ) , OMNICC is showing sometimes the cooldown text still on the nameplate of ELVUI.

**Comment by Tuller** [comment]
I think this one is fixed in the latest beta
