### ISSUE TITLE
Cooldown text not showing on actionbars

### ISSUE THREAD

**Issue by extexn** [tullamods/OmniCC#228]
Cooldown text is not showing on actionbars, except if it's an ability with charges and i have 1 or more charges left. Works fine with my weakauras. I use elvui actionbars with with Elvui's cooldown text disabled

**Comment by Ghaan** [comment]
I have had this happen to me on occasion too, but a quick /reload resolved it. Still a bug that exists though.

**Comment by lolo1337** [comment]
Happening to me too, when using PW: Radiance. would be nice to have this fixed
