### ISSUE TITLE
"Activate" finish effect animation issue.

### ISSUE THREAD

**Issue by Snichy** [tullamods/OmniCC#229]
I am having the same issue as #152 from back in 2016, and I notice a few others are too.  Getting unusual border highlighting issue, see below:

![masque issue](https://user-images.githubusercontent.com/36706613/44278724-e3ea6580-a246-11e8-882a-c9d473c63a85.JPG)

Not sure if this has been resolved yet?

**Comment by iperke** [comment]
Just tracked down the same issue to OmniCC - using blizzard's standard bars.

**Comment by Tuller** [comment]
The 8.0.2 beta actually removes this effect until I rewrite it.
