### ISSUE TITLE
Dominos (ationbar) rules not working

### ISSUE THREAD

**Issue by ehern87** [tullamods/OmniCC#230]
I can't get rules to correctly apply to Dominos action bars, it always just inherits the default profile. I've tried: ActionButton, Dominos, DomniosFrame. I have another set of rules for my unit frames that is working correctly.

Here is the /fstack:

![wowscrnshot_082518_140711](https://user-images.githubusercontent.com/41849866/44622673-30025f00-a872-11e8-86e2-44e5d7084776.jpg)

**Comment by Tuller** [comment]
You probably just want actionbutton as he pattern for those

**Comment by Ghaan** [comment]
The addon hasn't gotten an update for over a month now, hopefully there will be one at all...

**Comment by ehern87** [comment]
SOLVED: Dominos creates a new frame called "ChargeCooldown" when abilities are charging, adding this as a rule fixes my issue
