### ISSUE TITLE
OmniCC doesn't show the timer for the first spell [ELVUI TEMPLATE]

### ISSUE THREAD

**Issue by Sekorhex** [tullamods/OmniCC#231]
![unbenannt](https://user-images.githubusercontent.com/42946288/44999590-cd6e3900-afbe-11e8-9bff-b8aa1b709eba.PNG)

All time the first spell doesn't show the timer

**Comment by Tuller** [comment]
Can you try with the latest beta on Curse?
https://www.curseforge.com/wow/addons/omni-cc/download/2612843

Here's what I'm getting after I adjust the minimum size:
![image](https://user-images.githubusercontent.com/191239/45005206-12df3600-afc0-11e8-93d3-65c118954af0.png)

**Comment by Sekorhex** [comment]
The beta works now! But i use since yesterday tullacc

**Comment by Tuller** [comment]
This should be resolved in the latest beta release.

**Comment by Sekorhex** [comment]
Well i update OmniCC to 8.0.2-Beta1 and that is the result (look picture).

**Comment by Tuller** [comment]
Can you try with the latest beta?
