### ISSUE TITLE
Four errors when logging in

### ISSUE THREAD

**Issue by BlueNightSky** [tullamods/OmniCC#232]
When I log in, I get four errors, use 8.0.2-Beta1 version.
<1>：
`1x OmniCC_Config\panels\general-綜合.lua:284: attempt to index upvalue 'Cooldown' (a nil value)
OmniCC_Config\panels\general-綜合.lua:284: in function `SetSavedValue'
OmniCC_Config\widgets\slider.lua:54: in function <OmniCC_Config\widgets\slider.lua:49>
[C]: in function `SetValue'
OmniCC_Config\widgets\slider.lua:95: in function `UpdateValue'
OmniCC_Config\panels\general-綜合.lua:66: in function `UpdateValues'
OmniCC_Config\panels\general-綜合.lua:338: in main chunk
[C]: ?
[C]: in function `LoadAddOn'
OmniCC\main.lua:14: in function <OmniCC\main.lua:13>
[C]: in function `Show'
FrameXML\UIParent.lua:2614: in function `SetUIPanel'
FrameXML\UIParent.lua:2420: in function `ShowUIPanel'
FrameXML\UIParent.lua:2320: in function <FrameXML\UIParent.lua:2316>
[C]: in function `SetAttribute'
FrameXML\UIParent.lua:3141: in function `ShowUIPanel'
Oilvl\Oilvl-v8.0.1 BFA Alpha.lua:5545: in function `?'
Oilvl\Oilvl-v8.0.1 BFA Alpha.lua:5692: in function <Oilvl\Oilvl.lua:5691>

Locals:
self = OmniCCOptions_GeneralSpiral transparency {
 0 = <userdata>
 type = 3
 High = OmniCCOptions_GeneralSpiral transparencyHigh {
 }
 Low = OmniCCOptions_GeneralSpiral transparencyLow {
 }
 GetSavedValue = <function> defined @OmniCC_Config\panels\general.lua:287
 tooltip = "Sets the opacity of the dark spirals you normally
see on buttons when on cooldown."
 Thumb = OmniCCOptions_GeneralSpiral transparencyThumb {
 }
 Text = OmniCCOptions_GeneralSpiral transparencyText {
 }
 SetSavedValue = <function> defined @OmniCC_Config\panels\general.lua:282
 GetFormattedText = <function> defined @OmniCC_Config\panels\general.lua:291
 valText = <unnamed> {
 }
}
value = 1.0099999774247
(*temporary) = nil
(*temporary) = nil
(*temporary) = "base"
(*temporary) = "attempt to index upvalue 'Cooldown' (a nil value)"
parent = OmniCCOptions_General {
 CreateMinSizeSlider = <function> defined @OmniCC_Config\panels\general.lua:182
 AddWidgets = <function> defined @OmniCC_Config\panels\general.lua:18
 UpdateValues = <function> defined @OmniCC_Config\panels\general.lua:57
 NewSlider = <function> defined @OmniCC_Config\panels\general.lua:152
 CreateSpiralOpacitySlider = <function> defined @OmniCC_Config\panels\general.lua:278
 CreateScaleTextCheckbox = <function> defined @OmniCC_Config\panels\general.lua:112
 CreateMinDurationSlider = <function> defined @OmniCC_Config\panels\general.lua:161
 CreateMinEffectDurationSlider = <function> defined @OmniCC_Config\panels\general.lua:200
 CreateTenthsSlider = <function> defined @OmniCC_Config\panels\general.lua:253
 buttons = <table> {
 }
 CreateEnableTextCheckbox = <function> defined @OmniCC_Config\panels\general.lua:93
 sliders = <table> {
 }
 CreateMMSSSlider = <function> defined @OmniCC_Config\panels\general.lua:221
 NewCheckbox = <function> defined @OmniCC_Config\panels\general.lua:84
 GetGroupSets = <function> defined @OmniCC_Config\panels\general.lua:77
 0 = <userdata>
 CreateUseAniUpdaterCheckbox = <function> defined @OmniCC_Config\panels\general.lua:131
 CreateFinishEffectPicker = <function> defined @OmniCC_Config\panels\general.lua:302
}
Cooldown = nil
`

<2>：
`1x OmniCC_Config\panels\general-綜合.lua:231: attempt to call method 'ForAll' (a nil value)
OmniCC_Config\panels\general-綜合.lua:231: in function `SetSavedValue'
OmniCC_Config\widgets\slider.lua:54: in function <OmniCC_Config\widgets\slider.lua:49>
[C]: in function `SetValue'
OmniCC_Config\widgets\slider.lua:95: in function `UpdateValue'
OmniCC_Config\panels\general-綜合.lua:66: in function `UpdateValues'
OmniCC_Config\panels\general-綜合.lua:338: in main chunk
[C]: ?
[C]: in function `LoadAddOn'
OmniCC\main.lua:14: in function <OmniCC\main.lua:13>
[C]: in function `Show'
FrameXML\UIParent.lua:2614: in function `SetUIPanel'
FrameXML\UIParent.lua:2420: in function `ShowUIPanel'
FrameXML\UIParent.lua:2320: in function <FrameXML\UIParent.lua:2316>
[C]: in function `SetAttribute'
FrameXML\UIParent.lua:3141: in function `ShowUIPanel'
Oilvl\Oilvl-v8.0.1 BFA Alpha.lua:5545: in function `?'
Oilvl\Oilvl-v8.0.1 BFA Alpha.lua:5692: in function <Oilvl\Oilvl.lua:5691>

Locals:
self = OmniCCOptions_GeneralMinimum duration to display text as MM:SS {
 0 = <userdata>
 type = 3
 High = OmniCCOptions_GeneralMinimum duration to display text as MM:SSHigh {
 }
 Low = OmniCCOptions_GeneralMinimum duration to display text as MM:SSLow {
 }
 GetSavedValue = <function> defined @OmniCC_Config\panels\general.lua:234
 tooltip = "Determines the threshold
for showing a cooldown
in a MM:SS format."
 Thumb = OmniCCOptions_GeneralMinimum duration to display text as MM:SSThumb {
 }
 Text = OmniCCOptions_GeneralMinimum duration to display text as MM:SSText {
 }
 SetSavedValue = <function> defined @OmniCC_Config\panels\general.lua:225
 GetFormattedText = <function> defined @OmniCC_Config\panels\general.lua:241
 valText = <unnamed> {
 }
}
value = 1
(*temporary) = nil
(*temporary) = <table> {
 Destroy = <function> defined @OmniCC\core\timer.lua:125
 GetOrCreate = <function> defined @OmniCC\core\timer.lua:28
 ForActive = <function> defined @OmniCC\core\timer.lua:228
 Subscribe = <function> defined @OmniCC\core\timer.lua:107
 GetTimerText = <function> defined @OmniCC\core\timer.lua:143
 GetTimerState = <function> defined @OmniCC\core\timer.lua:210
 Update = <function> defined @OmniCC\core\timer.lua:69
 Unsubscribe = <function> defined @OmniCC\core\timer.lua:117
}
(*temporary) = "UpdateText"
(*temporary) = "attempt to call method 'ForAll' (a nil value)"
parent = OmniCCOptions_General {
 CreateMinSizeSlider = <function> defined @OmniCC_Config\panels\general.lua:182
 AddWidgets = <function> defined @OmniCC_Config\panels\general.lua:18
 UpdateValues = <function> defined @OmniCC_Config\panels\general.lua:57
 NewSlider = <function> defined @OmniCC_Config\panels\general.lua:152
 CreateSpiralOpacitySlider = <function> defined @OmniCC_Config\panels\general.lua:278
 CreateScaleTextCheckbox = <function> defined @OmniCC_Config\panels\general.lua:112
 CreateMinDurationSlider = <function> defined @OmniCC_Config\panels\general.lua:161
 CreateMinEffectDurationSlider = <function> defined @OmniCC_Config\panels\general.lua:200
 CreateTenthsSlider = <function> defined @OmniCC_Config\panels\general.lua:253
 buttons = <table> {
 }
 CreateEnableTextCheckbox = <function> defined @OmniCC_Config\panels\general.lua:93
 sliders = <table> {
 }
 CreateMMSSSlider = <function> defined @OmniCC_Config\panels\general.lua:221
 NewCheckbox = <function> defined @OmniCC_Config\panels\general.lua:84
 GetGroupSets = <function> defined @OmniCC_Config\panels\general.lua:77
 0 = <userdata>
 CreateUseAniUpdaterCheckbox = <function> defined @OmniCC_Config\panels\general.lua:131
 CreateFinishEffectPicker = <function> defined @OmniCC_Config\panels\general.lua:302
}
Timer = <table> {
 Destroy = <function> defined @OmniCC\core\timer.lua:125
 GetOrCreate = <function> defined @OmniCC\core\timer.lua:28
 ForActive = <function> defined @OmniCC\core\timer.lua:228
 Subscribe = <function> defined @OmniCC\core\timer.lua:107
 GetTimerText = <function> defined @OmniCC\core\timer.lua:143
 GetTimerState = <function> defined @OmniCC\core\timer.lua:210
 Update = <function> defined @OmniCC\core\timer.lua:69
 Unsubscribe = <function> defined @OmniCC\core\timer.lua:117
}
`

<3>：
`1x OmniCC_Config\panels\general-綜合.lua:259: attempt to call method 'ForAll' (a nil value)
OmniCC_Config\panels\general-綜合.lua:259: in function `SetSavedValue'
OmniCC_Config\widgets\slider.lua:54: in function <OmniCC_Config\widgets\slider.lua:49>
[C]: in function `SetValue'
OmniCC_Config\widgets\slider.lua:95: in function `UpdateValue'
OmniCC_Config\panels\general-綜合.lua:66: in function `UpdateValues'
OmniCC_Config\panels\general-綜合.lua:338: in main chunk
[C]: ?
[C]: in function `LoadAddOn'
OmniCC\main.lua:14: in function <OmniCC\main.lua:13>
[C]: in function `Show'
FrameXML\UIParent.lua:2614: in function `SetUIPanel'
FrameXML\UIParent.lua:2420: in function `ShowUIPanel'
FrameXML\UIParent.lua:2320: in function <FrameXML\UIParent.lua:2316>
[C]: in function `SetAttribute'
FrameXML\UIParent.lua:3141: in function `ShowUIPanel'
Oilvl\Oilvl-v8.0.1 BFA Alpha.lua:5545: in function `?'
Oilvl\Oilvl-v8.0.1 BFA Alpha.lua:5692: in function <Oilvl\Oilvl.lua:5691>

Locals:
self = OmniCCOptions_GeneralMinimum duration to display tenths of seconds {
 0 = <userdata>
 type = 3
 High = OmniCCOptions_GeneralMinimum duration to display tenths of secondsHigh {
 }
 Low = OmniCCOptions_GeneralMinimum duration to display tenths of secondsLow {
 }
 GetSavedValue = <function> defined @OmniCC_Config\panels\general.lua:262
 tooltip = "Determines the threshold
for showing tenths of seconds."
 Thumb = OmniCCOptions_GeneralMinimum duration to display tenths of secondsThumb {
 }
 Text = OmniCCOptions_GeneralMinimum duration to display tenths of secondsText {
 }
 SetSavedValue = <function> defined @OmniCC_Config\panels\general.lua:257
 GetFormattedText = <function> defined @OmniCC_Config\panels\general.lua:266
 valText = <unnamed> {
 }
}
value = 0
(*temporary) = nil
(*temporary) = <table> {
 Destroy = <function> defined @OmniCC\core\timer.lua:125
 GetOrCreate = <function> defined @OmniCC\core\timer.lua:28
 ForActive = <function> defined @OmniCC\core\timer.lua:228
 Subscribe = <function> defined @OmniCC\core\timer.lua:107
 GetTimerText = <function> defined @OmniCC\core\timer.lua:143
 GetTimerState = <function> defined @OmniCC\core\timer.lua:210
 Update = <function> defined @OmniCC\core\timer.lua:69
 Unsubscribe = <function> defined @OmniCC\core\timer.lua:117
}
(*temporary) = "UpdateText"
(*temporary) = "attempt to call method 'ForAll' (a nil value)"
parent = OmniCCOptions_General {
 CreateMinSizeSlider = <function> defined @OmniCC_Config\panels\general.lua:182
 AddWidgets = <function> defined @OmniCC_Config\panels\general.lua:18
 UpdateValues = <function> defined @OmniCC_Config\panels\general.lua:57
 NewSlider = <function> defined @OmniCC_Config\panels\general.lua:152
 CreateSpiralOpacitySlider = <function> defined @OmniCC_Config\panels\general.lua:278
 CreateScaleTextCheckbox = <function> defined @OmniCC_Config\panels\general.lua:112
 CreateMinDurationSlider = <function> defined @OmniCC_Config\panels\general.lua:161
 CreateMinEffectDurationSlider = <function> defined @OmniCC_Config\panels\general.lua:200
 CreateTenthsSlider = <function> defined @OmniCC_Config\panels\general.lua:253
 buttons = <table> {
 }
 CreateEnableTextCheckbox = <function> defined @OmniCC_Config\panels\general.lua:93
 sliders = <table> {
 }
 CreateMMSSSlider = <function> defined @OmniCC_Config\panels\general.lua:221
 NewCheckbox = <function> defined @OmniCC_Config\panels\general.lua:84
 GetGroupSets = <function> defined @OmniCC_Config\panels\general.lua:77
 0 = <userdata>
 CreateUseAniUpdaterCheckbox = <function> defined @OmniCC_Config\panels\general.lua:131
 CreateFinishEffectPicker = <function> defined @OmniCC_Config\panels\general.lua:302
}
Timer = <table> {
 Destroy = <function> defined @OmniCC\core\timer.lua:125
 GetOrCreate = <function> defined @OmniCC\core\timer.lua:28
 ForActive = <function> defined @OmniCC\core\timer.lua:228
 Subscribe = <function> defined @OmniCC\core\timer.lua:107
 GetTimerText = <function> defined @OmniCC\core\timer.lua:143
 GetTimerState = <function> defined @OmniCC\core\timer.lua:210
 Update = <function> defined @OmniCC\core\timer.lua:69
 Unsubscribe = <function> defined @OmniCC\core\timer.lua:117
}
`

<4>：
`1x OmniCC_Config\panels\general-綜合.lua:188: attempt to call method 'ForAll' (a nil value)
OmniCC_Config\panels\general-綜合.lua:188: in function `SetSavedValue'
OmniCC_Config\widgets\slider.lua:54: in function <OmniCC_Config\widgets\slider.lua:49>
[C]: in function `SetValue'
OmniCC_Config\widgets\slider.lua:95: in function `UpdateValue'
OmniCC_Config\panels\general-綜合.lua:66: in function `UpdateValues'
OmniCC_Config\panels\general-綜合.lua:338: in main chunk
[C]: ?
[C]: in function `LoadAddOn'
OmniCC\main.lua:14: in function <OmniCC\main.lua:13>
[C]: in function `Show'
FrameXML\UIParent.lua:2614: in function `SetUIPanel'
FrameXML\UIParent.lua:2420: in function `ShowUIPanel'
FrameXML\UIParent.lua:2320: in function <FrameXML\UIParent.lua:2316>
[C]: in function `SetAttribute'
FrameXML\UIParent.lua:3141: in function `ShowUIPanel'
Oilvl\Oilvl-v8.0.1 BFA Alpha.lua:5545: in function `?'
Oilvl\Oilvl-v8.0.1 BFA Alpha.lua:5692: in function <Oilvl\Oilvl.lua:5691>

Locals:
self = OmniCCOptions_GeneralMinimum size to display text {
 0 = <userdata>
 type = 3
 High = OmniCCOptions_GeneralMinimum size to display textHigh {
 }
 Low = OmniCCOptions_GeneralMinimum size to display textLow {
 }
 GetSavedValue = <function> defined @OmniCC_Config\panels\general.lua:191
 Thumb = OmniCCOptions_GeneralMinimum size to display textThumb {
 }
 tooltip = "Determines how big a frame must be to display text.
The smaller the value, smaller things can be to show text.
The larger the value, the bigger things must be.

Some benchmarks:
100 - The size of an action button
80  - The size of a class or pet action button
55  - The size of a target frame buff"
 SetSavedValue = <function> defined @OmniCC_Config\panels\general.lua:186
 Text = OmniCCOptions_GeneralMinimum size to display textText {
 }
 valText = <unnamed> {
 }
}
value = 50
(*temporary) = nil
(*temporary) = <table> {
 Destroy = <function> defined @OmniCC\core\timer.lua:125
 GetOrCreate = <function> defined @OmniCC\core\timer.lua:28
 ForActive = <function> defined @OmniCC\core\timer.lua:228
 Subscribe = <function> defined @OmniCC\core\timer.lua:107
 GetTimerText = <function> defined @OmniCC\core\timer.lua:143
 GetTimerState = <function> defined @OmniCC\core\timer.lua:210
 Update = <function> defined @OmniCC\core\timer.lua:69
 Unsubscribe = <function> defined @OmniCC\core\timer.lua:117
}
(*temporary) = "UpdateShown"
(*temporary) = "attempt to call method 'ForAll' (a nil value)"
parent = OmniCCOptions_General {
 CreateMinSizeSlider = <function> defined @OmniCC_Config\panels\general.lua:182
 AddWidgets = <function> defined @OmniCC_Config\panels\general.lua:18
 UpdateValues = <function> defined @OmniCC_Config\panels\general.lua:57
 NewSlider = <function> defined @OmniCC_Config\panels\general.lua:152
 CreateSpiralOpacitySlider = <function> defined @OmniCC_Config\panels\general.lua:278
 CreateScaleTextCheckbox = <function> defined @OmniCC_Config\panels\general.lua:112
 CreateMinDurationSlider = <function> defined @OmniCC_Config\panels\general.lua:161
 CreateMinEffectDurationSlider = <function> defined @OmniCC_Config\panels\general.lua:200
 CreateTenthsSlider = <function> defined @OmniCC_Config\panels\general.lua:253
 buttons = <table> {
 }
 CreateEnableTextCheckbox = <function> defined @OmniCC_Config\panels\general.lua:93
 sliders = <table> {
 }
 CreateMMSSSlider = <function> defined @OmniCC_Config\panels\general.lua:221
 NewCheckbox = <function> defined @OmniCC_Config\panels\general.lua:84
 GetGroupSets = <function> defined @OmniCC_Config\panels\general.lua:77
 0 = <userdata>
 CreateUseAniUpdaterCheckbox = <function> defined @OmniCC_Config\panels\general.lua:131
 CreateFinishEffectPicker = <function> defined @OmniCC_Config\panels\general.lua:302
}
Timer = <table> {
 Destroy = <function> defined @OmniCC\core\timer.lua:125
 GetOrCreate = <function> defined @OmniCC\core\timer.lua:28
 ForActive = <function> defined @OmniCC\core\timer.lua:228
 Subscribe = <function> defined @OmniCC\core\timer.lua:107
 GetTimerText = <function> defined @OmniCC\core\timer.lua:143
 GetTimerState = <function> defined @OmniCC\core\timer.lua:210
 Update = <function> defined @OmniCC\core\timer.lua:69
 Unsubscribe = <function> defined @OmniCC\core\timer.lua:117
}
`
Hope to help addon get better^^

**Comment by Tuller** [comment]
Did you remove both OmniCC folders from your addons directory before installing?
