### ISSUE TITLE
Cooldowns are showing only on the first profile

### ISSUE THREAD

**Issue by Znuff** [tullamods/OmniCC#233]
I use different profiles with OmniCC to only show cooldowns on specific frames with specific sizes.

After the update to Beta, I only see the cooldowns on the `BT4` frame, everything else is not showing up (`WeakAurasCooldown`, `SUFHeaderBoss`, `SUFUnitFocus`, `SUFUnitPet`, `SUFUnitPlayer`, `SUFUnitTargetAurabuffs`, `SUFUnitTargettarget`)

This is on `8.0.2-Beta1`.

**Comment by Znuff** [comment]
Follow UP:

Regarding SUF - my configuration had "Disable Blizzard Cooldown Count" enabled, because SUF provides a different option for "Disable OmniCC Cooldown Count".

Obviously I tried the option before making the ticket, but that cooldown text didn't actually show up until I unchecked the option *and* I reloaded my UI.

**Comment by Tuller** [comment]
I believe I fixed this one.
