### ISSUE TITLE
Latest beta and multiple charge abilities

### ISSUE THREAD

**Issue by Axaion** [tullamods/OmniCC#234]
Yes, i read the note where it says 

"OmniCC now obeys the Blizzard Cooldown:SetHideCountdownNumbers API method and will not display numbers on things that set it to true. A side effect of this is that abilities with charges will not display cooldown text until no charges remain."

Now while this is all well and good, it makes the beta well near unusable for sub rogues that relies on shadowdance and knowing its exact stack + cd

Just wanted to drop in that i hope you guys find a way around it so we can have that sweet timer back

**Comment by Ghaan** [comment]
Second this.
This was a big part of why the addon was so good.

**Comment by Tuller** [comment]
The plan is to find a non hacky way of doing this

**Comment by Tuller** [comment]
This should be fixed in the latest beta. OmniCC now keeps track of abilities with multiple cooldowns and displays them in order of soonest to expire.

**Comment by hollo6** [comment]
The cooldown text on my charge ability is now very small, is it intended or can I change it somehow?

**Comment by Tuller** [comment]
What addon are you using?

**Comment by hollo6** [comment]
For what? I have the CDs for all the other abilities/items with Beta4 and charges too in 8.0.1. Just missing the CD from abilities with charges in Beta4, haven't tried other Beta versions against this issue though.

**Comment by Tuller** [comment]
Your action bar, or whatever thing you have charges appear on

**Comment by hollo6** [comment]
I'm using Dominos for my action bars.

**Comment by Tuller** [comment]
Its possible text is smaller as I'm checking both the width and the height of the button for scaling.

**Comment by hollo6** [comment]
Right, my bad, the numbers are just so very small I thought it was the default. Gonna open a new ticket with updated information about this.
