### ISSUE TITLE
8.0.2-Beta1 does not obey text size

### ISSUE THREAD

**Issue by Znuff** [tullamods/OmniCC#236]
As per title, the `8.0.2-Beta1`  tag does not obey the text-size setting for "Under an hour" and "One hour or more".

My setings are to use a font size of 26 as base, and reducing the "Under an hour" and "One hour or more" text to 50%. This is not being obeyed right now.

**Comment by Tuller** [comment]
This should be fixed with the latest beta (8.0.2-beta2)
