### ISSUE TITLE
Finish Effect not working at all when triggered during global cooldown

### ISSUE THREAD

**Issue by sebo001** [tullamods/OmniCC#238]
As the title says, the'Finish Effects' work fine for me, **unless** they are triggered while the global cooldown is in effect. In that case, no effect is played at all. It seems to be like that with all of the effects. 

I noticed this with 8.0.1 and just checked with 8.0.2-Beta1 it's also the case. I tested with all other addons deactivated, anything more I could try?

**Comment by Tuller** [comment]
For this case, I probably want to send a finish event on timers stopped by the GCD.

**Comment by frozenjo** [comment]
Hi, is this still on the table to be implemented, cause the finish effect is kinda nice in fights but since it almost always aligne with the GCD, it never occurs. Thx in advance

**Comment by Tuller** [comment]
Yes, I'm just very lazy at implementing it

**Comment by Tuller** [comment]
The beta should fix this:
https://github.com/tullamods/OmniCC/releases/tag/9.0.0-beta
