### ISSUE TITLE
Bugs with threat plates and cc control

### ISSUE THREAD

**Issue by Addonman** [tullamods/OmniCC#240]
With i think yesterdays version i am getting 2 bugs.
first -double cooldowns in threat plates but for some reason cd from omnicc i am getting only some off times and not always.(hunter spell A murder of crows)
2nd-on top of usual cc control timers i am getting omnicc enourmus numbers on top of it- 3-5 times size of usual ones
Is there way to turn them off to get back to prevoius situation?

**Comment by Tuller** [comment]
Do you have screenshots?

**Comment by Addonman** [comment]
[https://imgur.com/4E6vlAd](url)
[https://imgur.com/cDQzkxt](url)

**Comment by Tuller** [comment]
Try with the latest beta (beta4)

**Comment by Addonman** [comment]
Its better,but also the same with double cooldowns.They are just nicer to see since they  are smaller.And on cc control inside icon not on top of it like in pic.

**Comment by Tuller** [comment]
My fix was mainly for the super large text on loss of control timers. 
For ThreatPlates, create a new group with the rule ThreatPlates and then disable text on it.

**Comment by Addonman** [comment]
Enable cooldown text dont work,still got cooldowns showing,Tried messing with min/max text size to show -didnt work as well.

**Comment by Tuller** [comment]
You might have to reload after doing so.

**Comment by Addonman** [comment]
Tested.Checked that enable cooldown text is off. Did /rl after . And then something odd happens.Whent to dummies and first time i attack target i get double cooldowns (deep wounds in my case) then its works like it should only TP cooldowns.

**Comment by Backupiseasy** [comment]
Developer of Threat Plates here. Today, I also realized that OmniCC cooldowns are shown on TP's auras. That's something that did not happen before the latest release, I think, as there is some sourcecode in TP that should prevent that. Basically

```
-- Get a clean version of the function...  Avoid OmniCC interference
local CooldownNative = CreateFrame("Cooldown", nil, WorldFrame)
Widget.SetCooldown = CooldownNative.SetCooldown
```

I don't really understand the code currently as it was already there before I started to maintain TP, but right now, it's no longer working, i.e., preventing OmniCC numbers from showing up.

**Comment by Tuller** [comment]
What the code you submitted is doing is attempting to grab a reference of the Cooldown.SetCooldown method prior to OmniCC hooking it. It later uses that reference like this:
```lua
-- Widget:UpdateAuraInformationIconMode(frame)
self.SetCooldown(frame.Cooldown, expiration - duration, duration + .25)
```
OmniCC is probably hooking the cooldown method before your code is called.  The preferred way of hiding OmniCC (and tullaCC and other stuff) is to add noCooldownCount = true to the cooldown:
```lua
-- Widget:CreateAuraFrameIconMode
frame.Cooldown:SetHideCountdownNumbers(true)
frame.noCooldownCount = true
```

**Comment by Backupiseasy** [comment]
Jep, saw that also when I looked into your code. With that, cooldown numbers are no longer shown. Thanks.
