### ISSUE TITLE
Big numbers on small icons on raid frames

### ISSUE THREAD

**Issue by cremor** [tullamods/OmniCC#242]
With 8.0.2-beta2 when I joined a raid my self buffs showed huge numbers on small icons on the Blizzard raid frames. After removing the buffs and buffing myself again the numbers were not shown again. So maybe the size check is not working when joining a raid?

edit: Also happend for a buff when I already was in a raid. But only for the first time I used it.

**Comment by Tuller** [comment]
Can you try with 8.0.2-Beta4?

**Comment by cremor** [comment]
Seems to be fixed, thanks.
