### ISSUE TITLE
Incorrect Cooldown/Numbers Showing

### ISSUE THREAD

**Issue by AlexTighe** [tullamods/OmniCC#243]
Using 8.0.2 Beta 2

Incorrect numbers are appearing on buff frames for buffs that should have no timer on them.
It seems to normally be that when it happens it is using the same duration as a duration next to it.

A reload will fix the issue.

**Comment by Tuller** [comment]
Can you try again with beta3?

**Comment by Tuller** [comment]
Looking at the code for Shadowed
```lua
-- Show the cooldown ring
if( not ShadowUF.db.profile.auras.disableCooldown and duration > 0 and endTime > 0 and ( config.timers.ALL or ( category == "player" and config.timers.SELF ) or ( category == "boss" and config.timers.BOSS ) ) ) then
	button.cooldown:SetCooldown(endTime - duration, duration)
	button.cooldown:Show()
else
	button.cooldown:Hide()
end
```
They're hiding cooldowns, but not actually clearing them, So I probably just need to adjust OmniCC to clear on hide

**Comment by cremor** [comment]
Could this also cause the following problem on the icons of Hekili (a rotation/priority helper addon)?
When I use an ability Hekili switches the icon to the next ability to use. But if this next ability doesn't have a cooldown (only the GCD) OmniCC 8.0.2-Beta3 actually shows the cooldown number of the ability that I just used (that was just cleared from the icon).

If this is something else I can also create a separate issue.

**Comment by Tuller** [comment]
Yes, it’s likely the same issue

**Comment by Tuller** [comment]
It should be fixed in beta4.

**Comment by AlexTighe** [comment]
Yeah, seems to be fixed for Shadowed Unit Frames at least, can't say for Hekili as I don't use it though.
