### ISSUE TITLE
remaining CD incorrecntly shown after being reset by an ability

### ISSUE THREAD

**Issue by hollo6** [tullamods/OmniCC#244]
With beta3, on a Guardian Druid, if Mangle gets reset by Gore, its remaining CD won't be updated, still shows the value from before the reset, despite the ability is in fact usable.

**Comment by Tuller** [comment]
Can you try with 8.0.2-Beta4?

**Comment by hollo6** [comment]
There is no change in this behavior with Beta4.

**Comment by Tuller** [comment]
Try with beta5.

**Comment by hollo6** [comment]
Seems fixed, thank you!
