### ISSUE TITLE
Cooldown numbers of previous ability on Hekili icon

### ISSUE THREAD

**Issue by cremor** [tullamods/OmniCC#245]
As explained in https://github.com/tullamods/OmniCC/issues/243#issuecomment-420348396 but since that issue was closed I'll open this new one. Still happens in beta4

**Comment by Tuller** [comment]
Try again with beta5. Instead of ignoring global cooldowns, OmniCC will hide any text instead.

**Comment by cremor** [comment]
Fixed, thanks.
