### ISSUE TITLE
Bartender/Omnicc Cooldown timers clash

### ISSUE THREAD

**Issue by P3N7Y** [tullamods/OmniCC#246]
I am not sure if this is a bug or some option I have missed.
![untitled](https://user-images.githubusercontent.com/43273657/45555949-0f567500-b832-11e8-9f8c-09368b582d98.png)

**Comment by Tuller** [comment]
I need to work on how I handle charge cooldowns for the LibActionButton case (bartender and other things)

**Comment by P3N7Y** [comment]
I have figured it out, me just being a fool sorry, I never turned of the "bliizard cd timers" off. Sorry for the waste of time ha.

**Comment by Tuller** [comment]
This was a bug, because OmniCC is meant to turn off blizzard's cooldown count while the addon is active. It'll be fixed in the next beta.
