### ISSUE TITLE
numbers too small on multiple charge abilities

### ISSUE THREAD

**Issue by hollo6** [tullamods/OmniCC#247]
Cooldown numbers on multiple charge abilities are too small, about half the size of others.
8.0.1:
![omnicc_801](https://user-images.githubusercontent.com/365584/45584304-6cedce80-b8d1-11e8-8917-681a3fc9a623.JPG)
8.0.2-beta5:
![omnicc_802b5](https://user-images.githubusercontent.com/365584/45584314-8e4eba80-b8d1-11e8-88a4-40810c5b8d66.JPG)

**Comment by Tuller** [comment]
Looks like in this case the recharging style is being incorrectly applied.

**Comment by hollo6** [comment]
Fixed in 8.0.3, thanks!
