### ISSUE TITLE
What is going on with this addon?!!

### ISSUE THREAD

**Issue by 40P3** [tullamods/OmniCC#252]
Cooldowns all over the place now!
I cannot get rid of cooldowns on raven addon's buff icons. It just don't go away, even though I've specifically selected not to show omnicc cooldowns on raven's bars/icons.

On my neuron bar I see multiple cooldowns, two three at a time (I use mod:ctrl/alt/shift on all my toons in a very standard 12button fashion so I assume these cooldowns show for modded skills on buttons)

Damn I haven't felt so perplexed in years what to push now! :( Can't really live without this fantastic addon!

Please fix!

**Comment by Tuller** [comment]
Raven seems to be hiding OmniCC when you disable it from the addon.

Neuron appears to have its own issues with charge cooldowns:
![image](https://user-images.githubusercontent.com/191239/45597235-dd125800-b996-11e8-8f8a-268182f47a36.png)
