### ISSUE TITLE
Cds on available consumables

### ISSUE THREAD

**Issue by Caza4** [tullamods/OmniCC#253]
As you can see my potions/hs have a 48 days cds while they are available.
![wowscrnshot_091618_162246](https://user-images.githubusercontent.com/43317711/45597489-6e9cbc80-b9cd-11e8-948a-1c3ada3ce6a9.jpg)

**Comment by Tuller** [comment]
What addon are you using to display that?

**Comment by Caza4** [comment]
That's a WA but I have the same issue with ElvUI NoDuration Buffs

**Comment by Tuller** [comment]
This _might_ be fixed with 8.0.6, as timer text should go away when a cooldown is no longer visible.
