### ISSUE TITLE
No numbers - using Bartender

### ISSUE THREAD

**Issue by aggietallboy** [tullamods/OmniCC#255]
We're back to default... I miss my numbers :)

**Comment by Tuller** [comment]
OmniCC appears to show up fine on Bartender for me, are you getting any lua errors?

**Comment by exidtv** [comment]
I got the same error now, numbers are not showing up on bartender anymore i tried to strip down to just omnicc and bartender removing all other addons problem still there.

**Comment by Tuller** [comment]
Can you play around with the minimum size slider?

**Comment by exidtv** [comment]
> Can you play around with the minimum size slider?

That actually did solve it for me but the minimum display text was also set extremely high mine was set to 30sec by default lowering that down to 10sec and playing around with the size fixed it for me.

**Comment by Tuller** [comment]
This is probably fixed in 8.0.5 as I made the size checks a bit more consistent
