### ISSUE TITLE
2 countdowns on tidyplates continued 

### ISSUE THREAD

**Issue by aden928** [tullamods/OmniCC#256]
After yesterday's update, I found 2 timers running on debuffs. I belive one is from omnicc and the other is from the original tidy plates iteself. I tried to disable omnicc, and it shows only 1 timer. I want to keep using omnicc, is there any solutions to it? Not sure what's been changed from yesterdays update.
![wowscrnshot_091718_011031](https://user-images.githubusercontent.com/43330481/45606845-864c6300-ba16-11e8-8eef-783585c2c49a.jpg)

**Comment by Tuller** [comment]
TidyPlates is responsible for disabling its own timer. For OmniCC, you can just add Plate to a group disable showing timers in that group.

**Comment by Luxocracy** [comment]
Hey, I maintain the TidyPlatesContinued project on GitHub. I noticed your Wiki states that there is a way for addon authors to prevent OmniCC from showing up, yet I can't seem to find any mention of how to actually go about doing so.

So I was wondering if you could point me in the right direction?

**Comment by Tuller** [comment]
for each cooldown, set noCooldownCount = true

**Comment by Luxocracy** [comment]
Thank you, love your addon as well, been using it since forever ;)
