### ISSUE TITLE
Sometimes shows CD numbers on small buff icons

### ISSUE THREAD

**Issue by cremor** [tullamods/OmniCC#259]
I've configured OmniCC to not show for icons below 55. This usually works correctly, but today I noticed that sometimes it shows numbers on the buff icons in the Blizzard raid frames. These numbers are extremely small, you can't really read them. I don't know what triggers the problem, but during a 3 hour raid I've seen it 4 or 5 times.

Using version 8.0.4

**Comment by Tuller** [comment]
This might be fixed in 8.0.5 as I made the size checks a bit more consistent

**Comment by Tuller** [comment]
This may be fixed with 8.0.5

**Comment by Kressless** [comment]
I'm still getting this Issue as well. 8.05 hasn't fixed it.

**Comment by Neurotoxin001** [comment]
it's still shows cd's even with 8.0.6:
![image](https://user-images.githubusercontent.com/39812401/45948881-cdd08180-c00a-11e8-8709-91b8c2068a5d.png)

When I untarget char and target it again - cd's dissapears:
![image](https://user-images.githubusercontent.com/39812401/45948920-eb9de680-c00a-11e8-852b-3832847d8b4d.png)

**Comment by Tuller** [comment]
Try again with 8.0.8

**Comment by Neurotoxin001** [comment]
Still not fixed:
![image](https://user-images.githubusercontent.com/39812401/46332120-033d2680-c62c-11e8-9861-49d95e787b4d.png)

**Comment by Tuller** [comment]
Can you try with a larger minimum size value?

**Comment by Neurotoxin001** [comment]
It's been 56, but it's random, not always showing. I think 56 is enough to hide it, why larger? It's start showing always at 47.

**Comment by Tuller** [comment]
The scale value is dependent on the size of buffs/debuffs. 60 will definitely hide them all.

**Comment by Neurotoxin001** [comment]
I have 56 and my buffs is showing, target buffs is not, but sometimes target buffs is start showing.

**Comment by Tuller** [comment]
60 is a good value for me to hide everything. Buff/debuff sizes on the blizzard frames can vary in size depending on role/class/target.

**Comment by Neurotoxin001** [comment]
> 60 is a good value for me to hide everything. Buff/debuff sizes on the blizzard frames can vary in size depending on role/class/target.

I don't need to hide **everything**, I need to hide only target buffs, and 56 is working before, but now it's bugs and showing cds sometimes. This is a bug.
