### ISSUE TITLE
Flare and shine finish effects fills entire screen

### ISSUE THREAD

**Issue by Niialy** [tullamods/OmniCC#260]
After the last update when using Echo of the Elements(Which makes so that you have 2 charges of lava burst, riptide etc) as a resto shaman, made it so that my first lava burst that gets ready after using both charges makes the finish effects flare and shine fill the entire screen.
100% reproduction rate. Works fine with the other finish effects.
I've tried to play around with my other abilities but it seems like it's only the first lava burst that gets ready that triggers it.

**Comment by Tuller** [comment]
This is probably fixed in 8.0.5
