### ISSUE TITLE
Timers randomly not showing

### ISSUE THREAD

**Issue by fatfrick** [tullamods/OmniCC#263]
Sometimes timers are not being shown (about 50% of the time) over the enemy's head on DoT abilities.  I've tried several different patches of omnicc and the issue still persists regardless of patch.  Also is there an alternative to change the spiral color? idk why you would take this function out, the default spiral is way to dark.

**Comment by fatfrick** [comment]
> What are your minimum size settings?
> The spiral stuff was taken out of OmniCC due to it having a significant performance impact.

Ive always kept it at 55 and ive tried several different numbers the issue still occurs, this issue only started happening during/after the BETA omnicc patches for bfa.

**Comment by Tuller** [comment]
Try with 8.0.8
