### ISSUE TITLE
Eye Beam CD not displaying correctly

### ISSUE THREAD

**Issue by BuurmanDeBuurman** [tullamods/OmniCC#266]
On my weakaura, Eye beam cooldown it will show 30 for the entire duration of the cooldown and then the number will disappear only once it has gone off cooldown. When I reloaded my UI it fixed it for one use, but then it went back to getting stuck again.

**Comment by BuurmanDeBuurman** [comment]
Update: It seems like the same issue is occurring for Barrage on a hunter for a very similar weak aura that is just an icon that shows the cooldown of the ability. So it's not exclusive to Eye Beam.

**Comment by andreiunuchak** [comment]
I have same issue with "Lose Control" addon. Often Counterspell stuck at max 6 sec.
![wowscrnshot_092918_121113](https://user-images.githubusercontent.com/43380444/46243914-7c950900-c3e1-11e8-949b-faf82cf9fbe4.jpg)

**Comment by BuurmanDeBuurman** [comment]
Yeah, it's actually not displaying a countdown, but just the max duration on a plethora of spells across all my characters. Mostly the ones with 1-10 min cooldowns.

**Comment by andreiunuchak** [comment]
Reproduces in 8.0.7

**Comment by Tuller** [comment]
I think this is fixed in 8.0.8, reopen if it is not
