### ISSUE TITLE
CD text is different since V8.0.1 - Blends in with the CD swirl effect. Very hard to see.

### ISSUE THREAD

**Issue by Walkinjunior** [tullamods/OmniCC#267]
The issue i'm talking about is where any CD text duration on a WA or such is blending into the swirl effect making it very hard to see at times and it looks horrible. I'm use to the way the CD timer was the past few years and i'm not sure if this is an intended change or not?

The issue: V8.0.7
![image](https://user-images.githubusercontent.com/43676252/46211033-61b38d80-c32a-11e8-8cfe-176b9c6c5bf9.png)

The way it was for years: V8.0.1
![image](https://user-images.githubusercontent.com/43676252/46211179-c969d880-c32a-11e8-9dd2-d7022b5f05d1.png)

This happens on pretty much anything that is using the omnicc text for the CD swirl timer. The above picture is on the Raven addons custom debuff tracker, but it does the same thing on weakauras too.

I Believe stack text also has the same issue.

**Comment by Tuller** [comment]
It’s s bug
