### ISSUE TITLE
Fonts errors within TellMeWhen and 8.0.7 Omnicc

### ISSUE THREAD

**Issue by Guoyyxiang** [tullamods/OmniCC#269]
After updated the latest version 8.0.7 Omnicc, I found that the timer fonts above the Tellmewhen's icons have changed to green color and smaller, like the figure shows as below, especially cant change their colors while the time is flowing which would change from yellow to red as the usual. Finally, I found I can only adjust the fonts' color and size by adjusting the "restoring charges" settings in Omnicc configuration. Is there any problem with the compatibility between Omnicc and TellMeWhen, or any mistacke setting in my addons?
![_20180930150840](https://user-images.githubusercontent.com/43718946/46255331-45e8ec80-c4ce-11e8-80a3-3a4d2a729130.png)

**Comment by Tuller** [comment]
whoops, I left some example code in for this :P

**Comment by Tuller** [comment]
This is fixed in 8.0.8
