### ISSUE TITLE
Display of CD Numbers on AddOns

### ISSUE THREAD

**Issue by XeeLiao** [tullamods/OmniCC#270]
Hi,

i have the problem with OmniCC that it shows the CD numbers on the small buffs on Shadow Unit Frames, Tidy Plates Widgets and on the Honor Level Display of Blizzard

**Comment by Tuller** [comment]
What version of your running?

**Comment by XeeLiao** [comment]
Iam using 8.0.7, can confirm it is from OmniCC, as i disable OmniCC it disappears from TidyPlates, SuF Buffs on Frames and the Honor Level

**Comment by XeeLiao** [comment]
![tdp](https://user-images.githubusercontent.com/41451315/46260953-375dfd80-c4ed-11e8-87bc-568093b9484a.png)

example of the omnicc numbers appearing on TidyPlates

![suf](https://user-images.githubusercontent.com/41451315/46260965-4c3a9100-c4ed-11e8-9c85-747811933a6e.png)

this is an example where there are tiny omnicc numbers on the Buff Display of SuF ( Rejuvenation on a Raid Frame here )

Display of OmniCC on Honor Level is not always there, only sometimes.

**Comment by Tuller** [comment]
Try with 8.0.8

**Comment by XeeLiao** [comment]
It does seem like it is gone on Shadowed Unit Frames, but on the TidyPlates Widgets the numbers of OmniCC are still there.

**Comment by Tuller** [comment]
Are you using tidyplates continued? I know they asked me about how to filter out omnicc. You can also make a group in omnicc with the rule plate to disable text

**Comment by Ther1sh** [comment]
Hi. same problem here. 
Saw a couple of ur responses about the rule in omnicc.
Can u please link or make some instruction for stupid people like myself :(

ty

**Comment by Tuller** [comment]
I’m also planning on doing some adjustments to the configuration UI to make it a bit easier to deal with. That’s after clearing the rest of the bugs from the queue though

**Comment by Ther1sh** [comment]
That would be great, thx again!
