### ISSUE TITLE
Many things are broken with 8.0.7.

### ISSUE THREAD

**Issue by Azortharion** [tullamods/OmniCC#271]
I had some issues with my CD's getting stuck before 8.0.7. Since updating, I've had:

1) The cooldown of long-CD spells will not display instantly when I press a button. The number will disappear for 1 second and then show up properly.

2) Sometimes the wrong CD will display for a while. If I use A Murder of Crows, a spell with a 1-minute cd, it will sometimes show "50" for 1 second before moving back to 58 and counting down properly.

3) On my ElvUI Target/Player Frames where it shows buffs and debuffs, the timer duration will randomly jump around. It will go to 2.0, then up to 3.0, then back to 1.0. Numbers will also pop in and out of existence or change to random numbers for no reason, see this gif: https://gfycat.com/FinishedEuphoricHairstreak

And on top of all this my CD's will sometimes get stuck anyway.

I streamed a whole night with these issues, you can go to any point in the VoD you want and probably see the effects. Here's an example of me using Bestial Wrath (1min30s cd) and it briefly showing "0.6" before moving back to its normal CD: https://gfycat.com/SmoothLinedHarpseal

I hope some of this helps.

**Comment by Tuller** [comment]
Try with 8.0.8
