### ISSUE TITLE
text formatting

### ISSUE THREAD

**Issue by Translitdk** [tullamods/OmniCC#273]
This is the right text formatting https://i.imgur.com/TUB4nTT.gif it goes from **1m** and then to **59**

But for spells with flat CDs, like **1m**, **2m**, **3m** and so on it is formatted as **n:60** when cd has started, not **1m** https://i.imgur.com/C8laNVc.gif

is it supposed to work like that?

**Comment by Tuller** [comment]
Looks like it’s catching the MM:SS format unintentionally
