### ISSUE TITLE
First Actionbar being treated differently than the rest

### ISSUE THREAD

**Issue by Malagron** [tullamods/OmniCC#275]
OmniCC is treating the first actionbar (Provided by Dominos) differently than others. On attached, Vanish is on the first, and Adrenaline Rush is not. If I change settings such as size or font, they apply to Adrenaline Rush, but not Vanish (or any other ability on that bar). If the only thing I do is disable OmniCC, the cooldowns on both will disappear entirely. All other behaviour (colour settings for instance) is consistent with OmniCC, but it is as if it is treating that one bar with default unmodifiable settings.

![cooldown](https://user-images.githubusercontent.com/43822721/46424826-65af2900-c6f7-11e8-9b6e-b38b853bb8c1.PNG)

**Comment by Tuller** [comment]
Do you have groups set up?

**Comment by Malagron** [comment]
Ah it was a groups thing. Looked around for options that might have had an impact, didn't think to look there. Sorry, and thanks!
