### ISSUE TITLE
Omni CC not showing cooldown numbers

### ISSUE THREAD

**Issue by cars11** [tullamods/OmniCC#276]
since updating past 8.0.4 the addon doesn't show any numbers on the icons anymore.
using Dominos as my bar addon

bugsack error:

4x OmniCC\main.lua:48: attempt to call method 'WatchCooldowns' (a nil value)
OmniCC\main.lua:48: in function `?'
OmniCC\main.lua:12: in function <OmniCC\main.lua:11>

Locals:
self = OmniCC {
 0 = <userdata>
 ADDON_LOADED = <function> defined @OmniCC\main.lua:43
 StartupSettings = <function> defined @OmniCC\settings\settings.lua:24
 PLAYER_LOGIN = <function> defined @OmniCC\main.lua:55
 PLAYER_ENTERING_WORLD = <function> defined @OmniCC\main.lua:51
 GetGroupSettings = <function> defined @OmniCC\settings\groups.lua:62
 GetVersion = <function> defined @OmniCC\settings\settings.lua:103
 StartupGroup = <function> defined @OmniCC\settings\settings.lua:54
 GetCooldownSettings = <function> defined @OmniCC\settings\groups.lua:34
 New = <function> defined @OmniCC\main.lua:73
 GetCooldownGroupID = <function> defined @OmniCC\settings\groups.lua:38
 AddGroup = <function> defined @OmniCC\settings\groups.lua:78
 UpdateGroups = <function> defined @OmniCC\settings\groups.lua:100
 Startup = <function> defined @OmniCC\main.lua:8
 sets = <table> {
 }
 FX = <table> {
 }
 UpgradeSettings = <function> defined @OmniCC\settings\settings.lua:42
 GetButtonIcon = <function> defined @OmniCC\main.lua:87
 GetGroupIndex = <function> defined @OmniCC\settings\groups.lua:68
 PLAYER_LOGOUT = <function> defined @OmniCC\main.lua:63
 RemoveGroup = <function> defined @OmniCC\settings\groups.lua:88
 SetupCommands = <function> defined @OmniCC\main.lua:26
 Display = <unnamed> {
 }
 Timer = <table> {
 }
 CreateHiddenFrame = <function> defined @OmniCC\main.lua:79
}
event = "ADDON_LOADED"
(*temporary) = nil
(*temporary) = OmniCC {
 0 = <userdata>
 ADDON_LOADED = <function> defined @OmniCC\main.lua:43
 StartupSettings = <function> defined @OmniCC\settings\settings.lua:24
 PLAYER_LOGIN = <function> defined @OmniCC\main.lua:55
 PLAYER_ENTERING_WORLD = <function> defined @OmniCC\main.lua:51
 GetGroupSettings = <function> defined @OmniCC\settings\groups.lua:62
 GetVersion = <function> defined @OmniCC\settings\settings.lua:103
 StartupGroup = <function> defined @OmniCC\settings\settings.lua:54
 GetCooldownSettings = <function> defined @OmniCC\settings\groups.lua:34
 New = <function> defined @OmniCC\main.lua:73
 GetCooldownGroupID = <function> defined @OmniCC\settings\groups.lua:38
 AddGroup = <function> defined @OmniCC\settings\groups.lua:78
 UpdateGroups = <function> defined @OmniCC\settings\groups.lua:100
 Startup = <function> defined @OmniCC\main.lua:8
 sets = <table> {
 }
 FX = <table> {
 }
 UpgradeSettings = <function> defined @OmniCC\settings\settings.lua:42
 GetButtonIcon = <function> defined @OmniCC\main.lua:87
 GetGroupIndex = <function> defined @OmniCC\settings\groups.lua:68
 PLAYER_LOGOUT = <function> defined @OmniCC\main.lua:63
 RemoveGroup = <function> defined @OmniCC\settings\groups.lua:88
 SetupCommands = <function> defined @OmniCC\main.lua:26
 Display = <unnamed> {
 }
 Timer = <table> {
 }
 CreateHiddenFrame = <function> defined @OmniCC\main.lua:79
}
(*temporary) = "attempt to call method 'WatchCooldowns' (a nil value)"
ADDON_NAME = "OmniCC"

**Comment by cars11** [comment]
here is another one

747x OmniCC\main.lua:92: attempt to index upvalue 'Display' (a nil value)
OmniCC\main.lua:92: in function <OmniCC\main.lua:73>
OmniCC\main.lua:127: in function <OmniCC\main.lua:110>
[C]: in function `SetCooldown'
TipTac\ttAuras.lua:91: in function `DisplayAuras'
TipTac\ttAuras.lua:125: in function `SetupAuras'
TipTac\ttAuras.lua:164: in function `?'
TipTac\ttCore.lua:300: in function `SendElementEvent'
TipTac\ttCore.lua:676: in function `ApplyUnitAppearance'
TipTac\ttCore.lua:821: in function <TipTac\ttCore.lua:782>
[C]: ?
[C]: ?
[C]: ?
...TheUndermineJournal\libs\LibExtraTip\LibExtraTip.lua:482: in function <...TheUndermineJournal\libs\LibExtraTip\LibExtraTip.lua:476>

Locals:
cooldown = <unnamed> {
 0 = <userdata>
}
duration = 3600
minDuration = 2.0000000298023
settings = <table> {
 styles = <table> {
 }
 mmSSDuration = 0
 spiralOpacity = 1.0099999774247
 minDuration = 2.0000000298023
 xOff = 0
 tenthsDuration = 0
 fontOutline = "OUTLINE"
 minSize = 0.5
 minEffectDuration = 30.000000447035
 fontSize = 18
 yOff = 0
}
oldDisplay = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = true
(*temporary) = nil
(*temporary) = "attempt to index upvalue 'Display' (a nil value)"
Addon = OmniCC {
 0 = <userdata>
 countdownForCooldowns = "0"
 Startup = <function> defined @OmniCC\main.lua:7
 StartupSettings = <function> defined @OmniCC\settings\settings.lua:24
 PLAYER_LOGIN = <function> defined @OmniCC\main.lua:167
 PLAYER_ENTERING_WORLD = <function> defined @OmniCC\main.lua:163
 FindGroup = <function> defined @OmniCC\settings\groups.lua:48
 GetGroupSettings = <function> defined @OmniCC\settings\groups.lua:21
 GetVersion = <function> defined @OmniCC\settings\settings.lua:103
 GetGroup = <function> defined @OmniCC\settings\groups.lua:27
 StartupGroup = <function> defined @OmniCC\settings\settings.lua:54
 New = <function> defined @OmniCC\main.lua:185
 GetGroupIndex = <function> defined @OmniCC\settings\groups.lua:72
 UpdateGroups = <function> defined @OmniCC\settings\groups.lua:103
 Timer = <table> {
 }
 AddGroup = <function> defined @OmniCC\settings\groups.lua:82
 sets = <table> {
 }
 GetGroupSettingsFor = <function> defined @OmniCC\settings\groups.lua:13
 UpgradeSettings = <function> defined @OmniCC\settings\settings.lua:42
 GetButtonIcon = <function> defined @OmniCC\main.lua:199
 Cache = <table> {
 }
 PLAYER_LOGOUT = <function> defined @OmniCC\main.lua:175
 RemoveGroup = <function> defined @OmniCC\settings\groups.lua:92
 SetupHooks = <function> defined @OmniCC\main.lua:41
 ADDON_LOADED = <function> defined @OmniCC\main.lua:155
 CreateHiddenFrame = <function> defined @OmniCC\main.lua:191
 SetupCommands = <function> defined @OmniCC\main.lua:25
}
hooked = <table> {
 (null) = true
}
cooldown_OnHide = <function> defined @OmniCC\main.lua:55
active = <table> {
}
Display = nil
hideTimer = <function> defined @OmniCC\main.lua:64

**Comment by cars11** [comment]
It does seem that way, but I never came about to only partially install an addon. I installed the two folders both manually and through the twitch/cruse program, same result

**Comment by Tuller** [comment]
Are you still having issues?
