### ISSUE TITLE
Big CDs wrong CD showing

### ISSUE THREAD

**Issue by 333silas** [tullamods/OmniCC#277]
So i started useing an addon called Gladiusex with OmniCC to Show cd , it works perfectly fine for all abilitys but stuff like Divine Shield , Bop ( Blessing of Protection) , Life swap from Priest Show wrong  cooldown  timers  ( basically all abilities with high cd ) 

Does this have to do with Gldaiusex or sth with Omnicc

**Comment by Tuller** [comment]
Do you have screenshots?

**Comment by ChadCloman** [comment]
I am seeing this issue and do **NOT** have Gladiusex installed. The displayed time dropped to 2 hours after the actual time dropped below 1.5 hours, so I think it may be doubling the time somehow. Here's a screen print:

![omnicc - wrong time](https://user-images.githubusercontent.com/41342202/50431365-5d9afb80-0898-11e9-8d86-05f5ddf1675d.png)

**Comment by ChadCloman** [comment]
Some more information. I have several long cooldowns and am seeing the following:

1h24m showing as 2h
3h47m showing as 5h
7h57m showing as 9h

So it's not a doubling; rather, it appears to be adding an hour. Probably an off-by-one error somewhere.

**Comment by ChadCloman** [comment]
I found the error. In core/timer.lua, there is the following line, which is supposed to be the number of ms in a half hour:
`local HALF_HOUR = 5400000`
This is actually the value for 90 minutes. The correct value is:
`local HALF_HOUR = 1800000`

**Comment by ChadCloman** [comment]
Note also that the following is in that same file:
`local HOURS_THRESHOLD = 84600000 -- 23.5 hours`

The value given is 24.0 hours, not 23.5 hours.

**Comment by Tuller** [comment]
That would definitely cause issues :p
