### ISSUE TITLE
DoT Timers Not Showing on Enemy Nameplates

### ISSUE THREAD

**Issue by SensusRogue** [tullamods/OmniCC#280]
The title says it all, when DoTs are applied to a target the timers for them aren't showing up on the enemy nameplates. Here's what it looks like. DoT timers are showing on the portrait but not the nameplate. Anyone know how to fix this?

I've tried re-installing the addon and installing earlier versions but still have this issue.

![no debuff cds](https://user-images.githubusercontent.com/45022292/48454475-58b93700-e785-11e8-986c-95df6ae2f580.png)

**Comment by Tuller** [comment]
What does your minimum size setting look like?

**Comment by SensusRogue** [comment]
It looks like the issue was on my end. I had the minimum size set to 50 which is why it wasn't showing.
