### ISSUE TITLE
OmniCC and TidyPlates issue

### ISSUE THREAD

**Issue by estanayerza** [tullamods/OmniCC#283]
How do I disable omniCC cooldown numbers on TidyPlates DoTs/Debuffs? I didn't find any useful answers on other posts.
Thanks in advance.

![image](https://user-images.githubusercontent.com/20137751/48973868-68a80500-f028-11e8-81e7-5a4bc0dfdf04.png)

**Comment by Tuller** [comment]
Try adding TidyPlates to a group:
https://github.com/tullamods/OmniCC/wiki/What-are-Groups%3F

**Comment by estanayerza** [comment]
Where could I make a request for this issue to be fixed automatically, I've been seen lots of people on forums looking for a solution and then giving up because of the high complexity. Althought, thanks for the groups feature. It seems to have a hard learning curve but with a few tries anyone could pull something up. Thank you for your time, have a good one!

**Comment by Tuller** [comment]
It's on my list to provide a set of predefined groups that aren't enabled by default. One of the groups would be for hiding stuff on nameplates.
