### ISSUE TITLE
Automatically scale text to fit within frames not working

### ISSUE THREAD

**Issue by ChadCloman** [tullamods/OmniCC#285]
With the 8.1 release, the "Automatically scale text to fit within frames" option stopped working. Here's a screen print (previously the text was reduced to fit within the quickbar square):

![omnicc - fit](https://user-images.githubusercontent.com/41342202/50431428-e2861500-0898-11e9-82dc-29e1d4d42e66.png)

**Comment by Tuller** [comment]
At the moment, the algorithm only cares about the frame size (so that buffs have smaller text than action buttons), and not the string width.
