### ISSUE TITLE
Addon keeps disabling blizzard "Show numbers for cooldown" option

### ISSUE THREAD

**Issue by omgcows** [tullamods/OmniCC#287]
Pretty much what the title says, anytime i reload or relog the blizzard show numbers cooldown option unchecks itself. Is there anyway to prevent it from doing so because i only use the addon to see the icon of the CC on the unit frame.

**Comment by Tuller** [comment]
I'd need to add an option to disable this bit of code:
https://github.com/tullamods/OmniCC/blob/master/main.lua#L55

The majority of users don't actually need both running at the same time, which is why the setting is there in the first place

**Comment by omgcows** [comment]
> I'd need to add an option to disable this bit of code:
> https://github.com/tullamods/OmniCC/blob/master/main.lua#L55
> 
> The majority of users don't actually need both running at the same time, which is why the setting is there in the first place

So i should just edit the 0 to 1 and it should fix it?

**Comment by Tuller** [comment]
You can actually just comment out the login and logout lines here:
https://github.com/tullamods/OmniCC/blob/master/main.lua#L22

**Comment by omgcows** [comment]
Sweet, it worked. Thanks for the help and quick replies, I appreciate it.
