### ISSUE TITLE
Finish Effects no longer working with elvUI/Weakauras

### ISSUE THREAD

**Issue by infyn** [tullamods/OmniCC#288]
Running ElvUI 10.87 / S&L 3.5 and WeakAuras 2.11.3, the text still works as it should but finish effects are no longer appearing.

I have tried disabling various addons but I don't really have anything else that alters action bars as I've exclusively used OmniCC for quite a while. No addon changes recently either.

Any additional troubleshooting I can do to help or try to solve this problem? I'm not even sure if anyone else is experiencing this but me.

**Comment by Tuller** [comment]
What action bars are you using?

**Comment by Tuller** [comment]
Both of these are timing dependent. Essentially what is happening is that the cooldowns are being hidden before the timer properly expires. I'm still looking into how to properly solve this one.

**Comment by EigenTheory** [comment]
I am having this issue as well. Is there a fix for this anywhere?

**Comment by Tuller** [comment]
No, nothing yet.

**Comment by Tuller** [comment]
The latest beta should theoretically fix this.
https://github.com/tullamods/OmniCC/releases/tag/9.0.0-beta
