### ISSUE TITLE
Minimum Size to Display Text

### ISSUE THREAD

**Issue by DekelWarrior** [tullamods/OmniCC#289]
Hello, I am having issues from time to time having the default unit frames buffs/debuffs showing text sometimes. I have the minimum text size set so when the larger buffs/debuffs applied by the player show up, they have cooldown text/numbers on them, but when the smaller buffs/debuffs applied by people besides the player show up, since they are smaller, not show cooldown text. From time to time, the smaller icons that I have set not to show cooldown text, will randomly show cooldown text and I have no idea why. Maybe this is a problem with the addon? I have had this problem for a couple of months now.

**Comment by Tuller** [comment]
What version are you running? (/occ version)

**Comment by DekelWarrior** [comment]
8.1.1

**Comment by Tuller** [comment]
I think this is fixed.
