### ISSUE TITLE
Performance question

### ISSUE THREAD

**Issue by jakabszili13** [tullamods/OmniCC#291]
If I make a ruleset to only display cooldowns on my grid2 addon debuffs and buffs, would that reduce the cpu usage?
Sorry that it’s not an issue, rather just a question, but I hope that i will get an answer.  Thanls

**Comment by Tuller** [comment]
This one is pretty much summed up as "It will probably reduce CPU usage, but maybe not by enough to be noticeable."

A few factors influence the overall CPU usage of OmniCC:
* How many **distinct** cooldowns we are currently displaying text for. Distinct here means "same start time, same duration, same OmniCC group",
* How much time is remaining on each cooldown we're displaying text for. On average, the closer a timer is to expiring, the more frequently OmniCC updates it.

Creating a rule to hide timers in OmniCC influences the first factor. Creating a rule can reduce the total number of active cooldowns OmniCC needs to keep track of, and thus can reduce overall CPU usage.
