### ISSUE TITLE
Using OmniCC will cause Player BUFF to lose cool text! 

### ISSUE THREAD

**Issue by Alarzzf** [tullamods/OmniCC#297]
Can you fix it？
![QQ图片20190704114048](https://user-images.githubusercontent.com/43119930/60697603-abff1600-9f1d-11e9-9097-4b1291a9f014.jpg)

**Comment by Alarzzf** [comment]
This is ElvUI

**Comment by Tuller** [comment]
It appears to be working for me. Perhaps reduce your minimum size setting?

**Comment by Alarzzf** [comment]
@Tuller okey，let me try.
