### ISSUE TITLE
Group priorities

### ISSUE THREAD

**Issue by jjholleman** [tullamods/OmniCC#299]
It would be nice to be able to set priorities on groups or sort them. As the way it currently works is the lowest groups override rules set in higher groups. This is causing difficulties in configuring rules with multiple groups. For example:  
 
right now I have an Ignore group set with rules for 3 specific WeakAuras icons. However, I have another Omnicc group with rules for all WeakAuras. Since I made this group after the ignore group it overrides the ignore rules. To fix this I have to make a new group with ignore rules for just those 3 WeakAura icons.  
![image](https://user-images.githubusercontent.com/6916881/63212372-e0144c00-c103-11e9-8860-baac8d262209.png)

If there was a way to alter the order of the groups so I can have my Ignore group load as last then this would be fine and I wouldn't need the extra "WeakAuras_ignore" group.
Or any other implementation that removes the need of my WeakAuras_ignore group.

**Comment by Tuller** [comment]
You can do it currently via editing saved variables, but there's nothing in the UI to do so currently.

**Comment by Tuller** [comment]
In 8.3.0, groups and rules have been broken up into two separate features. You can manually assign priorities to rules:
![image](https://user-images.githubusercontent.com/191239/68534874-aa14eb80-0331-11ea-8684-6396f9e89f75.png)
