### ISSUE TITLE
CPU usage

### ISSUE THREAD

**Issue by Ryanpode** [tullamods/OmniCC#300]
Just wanted to make sure this seems normal. I'm using OmniCC with Tellmewhen and ShadowedUF, so there are a lot of cooldowns being displayed at a time. 

I used a CPU tracking addon during a raid encounter (LFR Sivara), and the CPU usage keeps increasing over the entire fight. 

Here's the CPU addon chart:
https://imgur.com/LRO9xe6.png

This is an example of what my UI looks like on this fight, about halfway through the encounter. This is on Mythic on a different attempt, but the symptoms are consistent. There's a lot of CDs being rendered, but I can't think of why it would keep getting worse and worse.
https://i.imgur.com/I1heGdI.png

**Comment by Ryanpode** [comment]
Hey, update. It looks like the biggest culprit is having the target debuffs turned on in Shadowed. Even if I only have a few shown on the screen. Here's a graph of a different attempt on the same fight with target debuffs turned off. 
https://i.imgur.com/4S2szwx.png

**Comment by Tuller** [comment]
![image](https://user-images.githubusercontent.com/191239/63216881-df8fab80-c12b-11e9-9f4a-253b01c9de27.png)

That's some debug output for casting a single debuff on a target and waiting for it to expire. Cooldown:SetTimer is called about once per tick, with a slightly different start duration each time. This can potentially cause more CPU usage than necessary.

**Comment by Tuller** [comment]
Try this build and let me know if things improve a bit:
https://github.com/tullamods/OmniCC/releases/tag/8.2.4

**Comment by Ryanpode** [comment]
Looks like that likely did the trick. This was the same LFR encounter with the target debuffs turned on. 
https://i.imgur.com/oa3X8tk.png

**Comment by Tuller** [comment]
Yay. Shadowed basically hides a cooldown and then immediately shows it again with new values when refreshing timers. This was causing OmniCC to update a timer at a minimum of twice per frame. I've now altered it to do only a single update.
