### ISSUE TITLE
OmniCC cant get addon to work for Classic

### ISSUE THREAD

**Issue by Wowclassic12345** [tullamods/OmniCC#301]
Hello,
I tried downloading OmniCC for Classic before launch, but it says that its out of date in addons on interface menu.
But theres is no update?

best regards

**Comment by Tuller** [comment]
Omnicc doesn’t really require any code changes to run on classic, so if you enable out of date addons you should be good to go.

**Comment by Wowclassic12345** [comment]
ok, so if it says out of date, i should just let it keep running?

**Comment by Wowclassic12345** [comment]
and thanks for the quick answer

**Comment by Tuller** [comment]
Yes, you can just enable out of date addons and it should run fine.

**Comment by Wowclassic12345** [comment]
Thanks you for your answer. Have a good day.
Btw do you know anything about if Streamers on EU servers will affect the community? for example on Shazzrah?

**Comment by Tuller** [comment]
Nope, I'm just aware that Blizzard said that Shazzrah is overpopulated at launch. I'm not sure how things will look like 3-6 months after launch.
