### ISSUE TITLE
Broken: "Minimum duration to display text as MM:SS"

### ISSUE THREAD

**Issue by VideoPlayerCode** [tullamods/OmniCC#302]
Related: #77 

The option is totally broken.

Case One:

- Set "Minimum duration to display text as MM:SS" to 15 minutes
- Cast the Arcane Torrent blood elf racial (2 minute CD).
- It will show as 2:00 and count down as "mm:ss"...

Two:

- Set "Minimum duration to display text as MM:SS" to 2 minutes
- Cast the Arcane Torrent blood elf racial (2 minute CD).
- It will show as 2:00 and count down as "mm:ss"...

Three:

- Set "Minimum duration to display text as MM:SS" to 1.1 minutes
- Cast the Arcane Torrent blood elf racial (2 minute CD).
- It will show as 2m and will not count down as "mm:ss"... When it reaches 1:10 minutes left, the icon text changes from "2m" to "1:10", "1:09", etc...

Summary:

- The option seems to be behaving as "Maximum CD to display any cooldown as MM:SS" instead of minimum.
- That explains why setting it to 15 minutes always shows a CD on anything that has a longer than 1 minute CD.
- It also explains why setting it to 1.1 minutes (for example) will NOT display a "MM:SS" format until the cooldown has counted down to the "1.1 minutes remaining" mark.
- So to summarize, it looks at TIME REMAINING and will ONLY display "MM:SS" format if the time left is LESS THAN the value.

Fix:

- I assume it is as simple as changing the logic from "if cd remaining is less than the chosen value" to "if cd remaining is greater than the chosen value".
- Even after fixing it, there MAY be another bug: Let's say you set OmniCC to "minimum CD to show as MM:SS = 2 minutes" and you cast a spell with a 2 or more minute CD. Well, as soon as that CD gets below 2 minutes remaining, it may switch to "Xm" format instead? Or perhaps the cooldown text remains flagged as "use mm:ss" format since it started with a higher value. Either way I am referring to the weirdness in case Three above, and how that may affect things _after_ the main bug is fixed.

Workaround for everything for now: I have set my personal minimum CD to 15 minutes (the max value of the settings slider) to ensure that every skill >= 60 seconds and <= 15 minutes will show as "MM:SS" format.

**Comment by Tuller** [comment]
The labeling is poor, but the behavior is as expected at least: You're picking the threshold for when the timer transitions from showing minutes as Mm and instead shows MM:SS.

**Comment by VideoPlayerCode** [comment]
Oh, that actually makes sense! So the only problem is the description, then... it makes it sound like an "above this threshold, use MM:SS format", like all the other "minimum X" settings (which all operate on "above this, do X").

Can't really think of any short and clean descriptions right now, but for brainstorming purposes, perhaps mention something like "Switch to MM:SS format when time remaining is below: (the time slider)".

**Comment by Tuller** [comment]
8.3.0 finally actually has the updated text:
![image](https://user-images.githubusercontent.com/191239/68534835-34a91b00-0331-11ea-9378-9e04e079e595.png)
