### ISSUE TITLE
Classic - Show Debuff Timers Under Target Frame Not Working

### ISSUE THREAD

**Issue by Zeal0us** [tullamods/OmniCC#304]
![image](https://user-images.githubusercontent.com/19498786/63891825-154a5500-c9b4-11e9-8ab2-f0678ad28696.png)
I haven't played in a while, but I'm playing Classic at the moment and  could have sworn I remembered being able to use OmniCC to show the debuff/buff timers under my target's unit frame.  I have minimum size to display text set to 0 (I also tried 1).  Action bar cool downs do seem to work. 
  Anything obvious I might be missing, or is this a bug?
Current config:
![image](https://user-images.githubusercontent.com/19498786/63891993-8558db00-c9b4-11e9-8a3f-8f8e2c3ed07b.png)

**Comment by Tuller** [comment]
The stock target frames in wow classic don't actually show aura durations.

**Comment by omikron** [comment]
Is there any way around this?

**Comment by Tuller** [comment]
Other unit frames might show that information, or maybe someone has already written an addon to show cooldowns on target frame buffs/debuffs

**Comment by milofeynman** [comment]
I believe you also need https://github.com/rgd87/ClassicAuraDurations, but I have not gotten it to work with the latest OmniCC. I do know that a streamer has it working: 
![image](https://user-images.githubusercontent.com/31642277/63912973-2dda5f80-c9f4-11e9-82ac-329201260a52.png)

**Comment by shanempope** [comment]
@omikron Download the latest here: https://www.curseforge.com/wow/addons/classicauradurations/files and it should work. His github is out of date.

**Comment by Zeal0us** [comment]
> I believe you also need https://github.com/rgd87/ClassicAuraDurations, but I have not gotten it to work with the latest OmniCC. I do know that a streamer has it working using an older version of omnicc:
> ![image](https://user-images.githubusercontent.com/31642277/63912973-2dda5f80-c9f4-11e9-82ac-329201260a52.png)
> 
> UPDATE: Download the mod here: https://www.curseforge.com/wow/addons/classicauradurations and it will work.

That works, thanks
