### ISSUE TITLE
Classic:OmniCC Not Working

### ISSUE THREAD

**Issue by Sarkli** [tullamods/OmniCC#306]
I have this installed for Classic. It is updated. Since the first time i installed this it has said its compatible but when i log into the game it flags it as 'out of date'. Even when i turn it on regardless of that it still will not even load once im in game. No error messages or nothing.  I have the same issue with Bagnon and out of the 10 addons im using for Classic these are the only two that do not work at all. I assume you are aware but let me know if theres anything i can do to help you resolve the issue.

**Comment by codezeroapps** [comment]
I am having the same issue

**Comment by Mirza101** [comment]
Likewise, started at first with Out of Date error. And now everything is fine, but it simply does not function, no error messages, nothing..
