### ISSUE TITLE
Cooldown Alpha

### ISSUE THREAD

**Issue by Krimsun** [tullamods/OmniCC#31]
Would it be possible to add something like this http://www.wowinterface.com/downloads/info18991-CooldownAlpha.html to OmniCC? It alters the alpha on the whole button while the ability is on cooldown, it worked fine on its own till 4.3... in tandem with Dominoes and OmniCC...

**Comment by Tuller** [comment]
I’d rather not mess with the opacity of things other than the cooldown itself
