### ISSUE TITLE
Buff and debuff timers not refreshing on the Z-Perl player frame

### ISSUE THREAD

**Issue by alecjpav** [tullamods/OmniCC#311]
Video here: https://streamable.com/2fol3

To explain the video: Arcane Intellect and Frost Armor have a duration of 30 minutes, but the buff timer doesn't refresh when I cast it again and still displays 28 minutes despite it actually being 30 minutes. Reloading my UI fixes the issue, but it will just happen the next time I cast it again.

This seems to happen for every buff and debuff I've tested.

**Comment by Tuller** [comment]
This appears to be working for me, using 5.8.0 in classic.

**Comment by alecjpav** [comment]
Thanks to your comment on Curseforge, this issue was fixed by checking the OmniCC support button in Z-Perl's settings.
