### ISSUE TITLE
Latest OmniCC update for 8.2.5 added new frames

### ISSUE THREAD

**Issue by Translitdk** [tullamods/OmniCC#312]
**Running Software (issues missing this information will be deleted):**
 - Addon version: 8.2.5 (24.09.2019)
 - Server patch: [e.g. Build 8.0.1.27178] 
[23:17:51] Dump: value=GetBuildInfo() 
[23:17:51] [1]="8.2.0", 
[23:17:51] [2]="31478", 
[23:17:51] [3]="Aug 12 
 **Have you read the changelog? (please don't waste our time)**
 Mark if read.
yes
**Describe the bug**
after update CD frames added to azsharas UI widget on encounter start / widget 1st appear
**To Reproduce**
Steps to reproduce the behaviour:
start encounter with queen azshara
**Expected behaviour**
widget has no duration info so it shouldn't have this numbers
**Screenshots**
https://i.imgur.com/1gGe7v2.png
**Error Logs**
Type `/console scriptErrors 1` in the chat and reload the game. If an error window appears, write here the first message (labelled 1/Many) that appeared.
no errors in bugsack, just unnecessary cd numbers
**Additional context**
If the last update was just toc thing then im not sure why OmniCC started to add this. I didn't have any of it before the update

**Comment by Tuller** [comment]
Perhaps it’s a new thing with the patch? You can probably create a new group, add the frame, and then disable text on that group

**Comment by Translitdk** [comment]
It's an UI widget `C_UIWidgetManager.GetZoneControlVisualizationInfo(2043)` from 8.2 of Azshara encounter. For sure i am able to blacklist that, but in case more people will be affected with that (not even sure why, if the change of latest update was only the toc part) there might be more reports about it.

Will test it again with 8.2.5 release of today.
Also i made WA days back when Eternal Palace was released if somehow you need more info about this widget https://wago.io/AzsharaWidget

**Comment by mr-aleks** [comment]
I have the same thing, but there is still here
![image](https://user-images.githubusercontent.com/23143866/66343603-a669ff80-e954-11e9-9eef-d36e0abd07a4.png)

**Comment by wowTurron** [comment]
Can confirm both bugs above: 1. azshara UI widget AND 2. PVP window

**Comment by Tuller** [comment]
Does this still occur with the 8.3.x versions?

**Comment by Translitdk** [comment]
On PTR? https://i.imgur.com/UW3TzfU.png still the same

**Comment by Tuller** [comment]
I specifically mean with the 8.3 version of OmniCC:
https://www.curseforge.com/wow/addons/omni-cc/files/2831609

**Comment by Translitdk** [comment]
Oh. It doesn't appear on pvp frame anymore. Will check widget when i reach Azshara

**Comment by Translitdk** [comment]
Actually, on Azshara, i think, something jumped to one of my WAs.
https://i.imgur.com/ZUWEFzo.png

**Comment by Tuller** [comment]
Is this still happening for you?

**Comment by Translitdk** [comment]
Don't know really, since i didn't go on Azshara after 8.3 and addon updates.

**Comment by Translitdk** [comment]
https://i.imgur.com/ppv7cLB.png
https://i.imgur.com/5Dvlutu.png
it sometiems add CD to stuff w/o duraiton info anyway. Not sure what causes it

**Comment by Saxayone** [comment]
I seem to get the same kind of issue but with simple wa's that track infinite duration buffs/debuffs, sometimes it shows as no cooldown and other times it will show a random cd under 2mins that corresponds to no other cd's.

**Comment by Tuller** [comment]
I believe the original issue was resolved. The WA stuff should be split out into a different issue for now.
