### ISSUE TITLE
Retail: Cooldowntext disappear after reload

### ISSUE THREAD

**Issue by Momo666** [tullamods/OmniCC#313]
**Running Software (issues missing this information will be deleted):**
 - Addon version:
ElvUI 8.2
OmniCC 8.2.5 (current) - 8.2.0  (i testet the last 5 versions)
Retail Server patch: 8.2.5.32028

 **Have you read the changelog? (please don't waste our time)**
i read the changelog

**Describe the bug**
Im using ElvUI (ElvUI, Blizz cooldowntext disabled) and whenever i reload ("/rl"), the cooldowntext dissapears. But only on my player buffs, the target buffs are working perfectly. 
I also have (target/player) the exact same settings.
I also made a new ElvUI (default) profile (disabled every addon execpt ElvUI+OmniCC) and also missing cooldowntext on my player frame.

**Expected behaviour**
After a reload the cooldowntext should be on the player buffs.

**Screenshots**
after login (everything works fine)
https://puu.sh/Eoa23/6c449f71b4.jpg

after reload (missing text on spells)
https://puu.sh/Eoa0L/c8d8a7fb55.jpg

**Additional context**
-

**Comment by evereskan** [comment]
I also having this issue. When disabling OmniCC and using standart or ElvUI cooldowns all is fine. Happens only on player buffs tho. Please fix, it is kinda annoying to deal with. I need to relog game to fix it, reload not helping

**Comment by Tuller** [comment]
This appears to be fixed in 8.3
