### ISSUE TITLE
OmniCC doesn't work at all with classic after update

### ISSUE THREAD

**Issue by Satoriis** [tullamods/OmniCC#314]
I had omnicc working fine two weeks or so ago with wow classic, but after recent updates it doesn't show at all. There are no countdown timers on anything, even the config button doesn't appear. The addon is definitely selected to load, but none of it works. Sucks.

**Running Software (issues missing this information will be deleted):**
 - Addon version:
 - Server patch: [e.g. Build 8.0.1.27178]

 **Have you read the changelog? (please don't waste our time)**
 Mark if read.

**Describe the bug**

**To Reproduce**
Steps to reproduce the behaviour:

**Expected behaviour**

**Screenshots**

**Error Logs**
Type `/console scriptErrors 1` in the chat and reload the game. If an error window appears, write here the first message (labelled 1/Many) that appeared.

**Additional context**

**Comment by Tuller** [comment]
I believe this is likely twitch giving you the wrong version.
