### ISSUE TITLE
Retail and Classic versions

### ISSUE THREAD

**Issue by Racerx323** [tullamods/OmniCC#315]
**Running Software (issues missing this information will be deleted):**
 - Addon version: 8.2.5
 - Server patch: don't know

 **Have you read the changelog? (please don't waste our time)**
 Mark if read.

**Describe the bug**
Twitch keeps replacing the retail version of the addon with the classic version. I do not have classic installed. I opened a ticket with Twitch and they said it is an addon author issue.

**To Reproduce**
Update the addon in Twitch

**Expected behavior**
keep the correct version of the addon

**Comment by Tuller** [comment]
This one is on twitch's end, unfortunately. It might resolve itself once 8.3.0 hits.
