### ISSUE TITLE
Text preview

### ISSUE THREAD

**Issue by 1ps3** [tullamods/OmniCC#319]
**Is your feature request related to a problem? Please describe.**
In the recent beta 8.3 and the options update there is no longer a text preview for what cooldown text would look like. Obviously this isn't a big deal because it's quite easy test. Though getting cd text with a white backdrop in the interface would be really helpful. Even if it's just a fontstring that doesn't update. 

**Describe the solution you'd like**
Maybe putting it next to the "Add Theme" bar would be good.

**Comment by Tuller** [comment]
I plan on adding a preview button/panel. I  did like the big font selector but want a way to capture what things look like with every setting applied.

**Comment by Tuller** [comment]
![image](https://user-images.githubusercontent.com/191239/69486756-05bd9980-0e47-11ea-9b9e-a602df0a72ec.png)
I've added a preview button to the options menu.
