### ISSUE TITLE
Cooldown text bug with Elvui frames

### ISSUE THREAD

**Issue by foward1** [tullamods/OmniCC#320]
**Running Software (issues missing this information will be deleted):**
 - Addon version: 8.2.5
 - Server patch: 8.2.5.32494

 **Have you read the changelog? (please don't waste our time)**
 Yes

**Describe the bug**
So, in the latest updates of both elvui and omnicc, it seems like the cooldown text does not show for the player buffs within ElvUI raidframes( note that the debuffs text show just fine, only buffs seem to be affected). I use OmniCC for everything and i have no issues regarding action buttons, nameplates, weakauras etc. 

**Expected behaviour**
The cooldown text should show up on my raidframes buffs, i also tried changing omnicc settings to for cooldown text to show up on smaller icons with no effect.

**Screenshots**
[https://gyazo.com/a66651528c2ab62fc74be831658b9e4a](url)

**Additional context**
I did not change any settings, 1 week ago it was working just fine, it's a very recent bug it seems for me.

**Comment by Tuller** [comment]
On the OmniCC end, I would try decreasing the minimum size value. On the ElvUI side, check for an option to enable either OmniCC or cooldown count in general

**Comment by foward1** [comment]
On the ElvUI side i disabled all Elvui cooldown texts so, i only have omnicc showing my cooldowns.
Also i did decrease the size on the omnicc side, and this happens https://gyazo.com/6c2f3cd020472ebb742f3789173de141

All these icons are exactly same size since they are all buffs, but ones show cooldown and the others do not.

**Comment by Tuller** [comment]
Does this still occur with the 8.3.x versions?
