### ISSUE TITLE
Shaman's Frost Shock does not show cooldown text

### ISSUE THREAD

**Issue by BlueNightSky** [tullamods/OmniCC#321]
**Running Software (issues missing this information will be deleted):**
 - Addon version: 8.3.1
 - Server patch: Build 8.2.5.32638

 **Have you read the changelog? (please don't waste our time)**
 yes

**Describe the bug**
Shaman's Frost Shock does not show cooldown text

**Comment by Tuller** [comment]
Did you upgrade from 8.2.5 or 8.3? Any lua errors?

**Comment by BlueNightSky** [comment]
I seem to be upgrading from 8.2.3, and without any errors.
I have tried to delete the profile in the SavedVariables folder, but the shaman's frost shock still can't show the cooldown text, but the flame shock is normal, very strange.

**Comment by Tuller** [comment]
Is this on classic? As far as i'm ware, frost shock doesn't have a cooldown on retail.

**Comment by BlueNightSky** [comment]
> 
> 
> Is this on classic? As far as i'm ware, frost shock doesn't have a cooldown on retail.

I am really a fool, I didn’t find that the frost shock was originally without CD.
really sorry!
