### ISSUE TITLE
"Restoring charges" does not work with TMW addon

### ISSUE THREAD

**Issue by damegu04** [tullamods/OmniCC#323]
I use OmniCC in combination with TMW and everythng works fine except "Restoring charges". Even if my settings of "Restoring charges" are: scaling 100 % and color set as blue, cooldowns of spells with charges like "Chi Torpedo, Hammer of the Righteous" are even larger and have same color as the standard cooldown (Soon to expire or < minute) . Is anyone facing the same issue?

Thank you

**Comment by Tuller** [comment]
At the moment, detection of cooldowns that are recharging is limited to action buttons.
