### ISSUE TITLE
Font size glitched on Plater buffs

### ISSUE THREAD

**Issue by Ljoseph54** [tullamods/OmniCC#327]
When using abilities, the Omnicc timer on the Plater (the addon) buffs will have a huge font size. To fix it I have to press escape and re-target the enemy and then it is back to normal size. This only started happening after 8.3. You can see in the screenshot (it was hard to get a good one) that the smaller text is the font I have it set at. The text was originally big but when I targeted the enemy I had targeted in the screenshot, it turned normal. On the current target, you can see how the text is much bigger for some reason. In the second screenshot, you can see how one ability is normal size but the others are big. 
![Capture](https://user-images.githubusercontent.com/43244394/72478750-92ca0280-37a7-11ea-8aa4-89335a190d55.PNG)
![Capture1](https://user-images.githubusercontent.com/43244394/72478993-1257d180-37a8-11ea-931d-8cb4ce0c62e3.PNG)
Most of the time not all of them are big, some are normal and some are glitched. It is not consistent per ability (it doesnt happen on specific abilities. For example when I use Garrote, it sometimes has big text and it sometimes doesn't) so I know its not a setting I have enabled. Also I tried just disabling the text but I couldnt find a way to disable the Omnicc timer on just the plater abilities and not all of my abilities including the ones on the action bar. I looked it up but it appears the the UI changed and there is no "group" setting that all the old forums tell me to use. I know its a glitch so I would appreciate if you could tell me how to at least disable the text on just the plater addon. Thanks

**Comment by storfors** [comment]
Maybe you could use the new theme/rules to remove the text specifically from unit frames? But anyway I have the same problem. I did some quick playing around yesterday to try and fix it, and it might have to do with the adaptive sizing option?

**Comment by Mpaltazor** [comment]
i have same issue some times tiers are big sometimes normal when u click out the target it ok dont know seems they need to fix that

**Comment by CruelDrool** [comment]
I have exactly the same issue. I've reverted back to the previous version of OmniCC.

**Comment by Mpaltazor** [comment]
i did it aswell but timers doesent work at all

**Comment by Ljoseph54** [comment]
> Maybe you could use the new theme/rules to remove the text specifically from unit frames? But anyway I have the same problem. I did some quick playing around yesterday to try and fix it, and it might have to do with the adaptive sizing option?

I am not sure how to use the new themes option. I tried using it the same way the Groups option worked but when I added my rules for the Action bar nothing happened. Reverting back to the 8.2.5 version fixed my issue

**Comment by Tuller** [comment]
Here's how you can hide text on Plater with OmniCC 8.3:

First, create a new theme called Hide Text. Uncheck the display cooldown text box on this theme.
![image](https://user-images.githubusercontent.com/191239/72652673-90ba9c00-397f-11ea-820c-6a0c613a00e8.png)

Second, open up the rules pane, and create a new rule called Plater. Within this rule, do the following:
* Set the theme to Hide Text
* Add Plater to the patterns box

![image](https://user-images.githubusercontent.com/191239/72652714-d1b2b080-397f-11ea-91d5-b1d7d06f82c4.png)

**Comment by Tuller** [comment]
For the case of text being too big, make sure the Rezize cooldown text to fit within frames option is checked. Here's what i see with it checked:
![image](https://user-images.githubusercontent.com/191239/72652819-4259cd00-3980-11ea-8cca-348513a73720.png)

unchecked:
![image](https://user-images.githubusercontent.com/191239/72652846-63222280-3980-11ea-8398-79b3aee6ca4e.png)

**Comment by Mpaltazor** [comment]
Hmm i did step by step this and nothing change

**Comment by Mpaltazor** [comment]
https://gyazo.com/d9a6120ce379cf5480247b7cf453bdfc

**Comment by Mpaltazor** [comment]
[https://gyazo.com/d9a6120ce379cf5480247b7cf453bdfc](url)

**Comment by Mpaltazor** [comment]
[https://gyazo.com/85cc9fe06e43156385ea81fe2fe4adcc]

**Comment by Mpaltazor** [comment]
[https://gyazo.com/85cc9fe06e43156385ea81fe2fe4adcc](url)

**Comment by Tuller** [comment]
Are you still getting this with the latest version?

**Comment by storfors** [comment]
> Are you still getting this with the latest version?

No not since a week or so! I did notice today the text starting out too large, but adjusted just after a couple of frames. But it's definitely been fixed for me.
