### ISSUE TITLE
raid frame buff / debuff cooldown

### ISSUE THREAD

**Issue by matio19** [tullamods/OmniCC#328]
after 8.3 update i found OmniCC cooldowns on my blizzard raid frame
![image](https://user-images.githubusercontent.com/59982889/72571303-e59adb80-38c7-11ea-96d1-b64700f8187c.png)

is it possible to disable it?

**Comment by Tuller** [comment]
Try increasing the minimum cooldown size setting to something a bit larger

**Comment by Tuller** [comment]
I believe this was fixed via 8.3.4
