### ISSUE TITLE
omnicc not displaying cooldown on abilities times longer than 59 seconds

### ISSUE THREAD

**Issue by Kressless** [tullamods/OmniCC#330]
Just as the title says, timers/cooldowns are not displaying on icons if they are a minute or longer.

Even with the minimum cooldown duration set as low as possible, and the preview properly displaying the cooldown past 60 seconds. the ability cooldowns on my bars longer than 1 minute don't function correctly. 
![1](https://user-images.githubusercontent.com/43398673/73132717-6a81b400-4083-11ea-9358-adbbc40e176e.JPG)
![2](https://user-images.githubusercontent.com/43398673/73132719-6b1a4a80-4083-11ea-87bb-57d6e35edc76.JPG)
![3](https://user-images.githubusercontent.com/43398673/73132720-6ce40e00-4083-11ea-93b4-7afc42555dbf.JPG)
![3](https://user-images.githubusercontent.com/43398673/73132721-6d7ca480-4083-11ea-922c-3c982b333004.JPG)

**Comment by Kressless** [comment]
![4](https://user-images.githubusercontent.com/43398673/73132722-7c635700-4083-11ea-87e1-fe631b296f25.JPG)

Cooldown of ability is 3 minutes but isn't showing even though it should be.

**Comment by Tuller** [comment]
I'm not seeing this on my end. What action bars are you using, and what happens if you reduce your minimum cooldown size?

**Comment by Kressless** [comment]
I'm using bartender and minimum cooldown size seems to be working normally. If i set min cooldown size to anything greater than 100, cds don't show up on my bar. (my bars are pretty much same size as default blizz bars).

I tried turning bartender off but it didn't change anything. Also it might be worth noting that even inside my spellbook, I'm getting the same bug.

**Comment by Kressless** [comment]
Just updated omnicc on twitch. everything seems to be working now :)
