### ISSUE TITLE
LUA Error

### ISSUE THREAD

**Issue by McGratton** [tullamods/OmniCC#331]
Hi There,

I'm very new to this sort of thing so I hope I'm submitting this correctly. I keep getting this LUA error which appears to be related to OmniCC as far as I can tell, but may be wrong. Here's what it says:

Date: 2020-02-26 18:26:49
ID: 1
Error occured in: Global
Count: 1
Message: ..\AddOns\OmniCC\main\effects\pulse.lua line 12:
   attempt to index local 'parent' (a nil value)
Debug:
   [C]: ?
   OmniCC\main\effects\pulse.lua:12: Run()
   OmniCC\main\core\fx.lua:38: Run()
   OmniCC\main\core\display.lua:90: OnTimerFinished()
   OmniCC\main\core\timer.lua:144: Update()
   OmniCC\main\core\timer.lua:85:
      OmniCC\main\core\timer.lua:85
Locals:

AddOns:
  Swatter, v8.2.6377 (SwimmingSeadragon)
  ClassicCastbars, vv1.2.7
  ClassicCastbarsOptions, v
  DBMCore, v1.13.38
  DBMDefaultSkin, v
  DBMStatusBarTimers, v
  Decursive, v2.7.6.6
  DejaClassicStats, v1303r001
  DruidBarClassic, v0.7.7
  GatherMate2, v1.45.5
  HHTD, v2.4.9.4
  honorspy, v1.7.3
  Informant, v8.2.6374 (SwimmingSeadragon)
  ItemRack, v
  LeatrixPlus, v1.13.50
  LoseControl, v1.03
  NameplateCCnTrinket, v11303-2
  OmniCC, v8.3.5
  Plexus, vv1.9.0
  Questie, v5.7.2
  RealMobHealth, v2.18
  Recount, vv1.13.3c
  SlideBar, v8.2.6375 (SwimmingSeadragon)
  Stubby, v8.2.6376 (SwimmingSeadragon)
  VendorPrice, v1.3.1
  BlizRuntimeLib_enUS v1.13.3.11303 <none>
  (ck=2a3)

Any help with this would be greatly appreciated.
Thanks!

**Comment by Tuller** [comment]
You are :), thanks for reporting this

**Comment by McGratton** [comment]
Good to know. I hope it helps.
