### ISSUE TITLE
WeakAuras timers are not showing up

### ISSUE THREAD

**Issue by kimitaka9x** [tullamods/OmniCC#332]
After updating WeakAuras2 addon, timers on buffs don't show up

**Comment by Peter-Day** [comment]
Will this get fixed before Shadowlands?

**Comment by Tuller** [comment]
This already works, as far as I can tell:
![image](https://user-images.githubusercontent.com/191239/92285819-dae39400-eef4-11ea-855f-ba61400f41c2.png)
