### ISSUE TITLE
Wrong interaction c Threat Plates (Classic) addon

### ISSUE THREAD

**Issue by NotaBeneRnD** [tullamods/OmniCC#334]
**Running Software (issues missing this information will be deleted):**
 - Addon version: 8.3.6-classic
 - Server patch: 1.13.5 (35395) (x64)

 **Have you read the changelog? (please don't waste our time)**
Mark if read. +

**Describe the bug**
Hello! I'm using Omnicc with NamePlate addon Threat Plates (Classic) v1.4.5. When i display Crowd Control (Widgets/Auras) it starts count +0.2 sec of real timer and stop at 0.2 sec (instead 0.0). I check it with Gouge Rank 1, which must incapacitating the opponent for 4 sec (i see 4.2sec - 0.2sec) and Sap Rank 1 (i see 25 - 0.2 sec). 
p.s. I checked durations with WeakAuras 2.18.2-classic with LibClassicDurations 1.64-classic and it show right info (4.0-0.0 & 25-0.0).
![WoWScrnShot_082420_155817](https://user-images.githubusercontent.com/68054544/91052578-53f80700-e62a-11ea-864d-261b04555b86.jpg)
![WoWScrnShot_082420_160004](https://user-images.githubusercontent.com/68054544/91052651-6eca7b80-e62a-11ea-8286-f202f9a5cfac.jpg)

**Comment by Tuller** [comment]
I would guess that Threat Plates is sending OmniCC inaccurate times
