### ISSUE TITLE
OmmiCC breaks my Escape keybind

### ISSUE THREAD

**Issue by nacedos** [tullamods/OmniCC#335]
**Running Software (issues missing this information will be deleted):**
 - Addon version: 8.3.6
 - Server patch: Build 8.3.7.35435

 **Have you read the changelog? (please don't waste our time)**
 Yes.

**Describe the bug**
Whenever i go into Interface-Addons-OmmiCC and press the list instead the '+' sign my escape keybind doesnt work untill I reload ui.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'Interface'
2. Click on 'Addons'
3. Scroll down to 'OmmiCC'
4. Click 'OmmiCC'
5. Escape key doesn't work anymore

**Expected behaviour**
It should open main settings window (?).

**Screenshots**
https://gyazo.com/d12f8cc25905cf0bd23be70dddf32c4e

**Error Logs**
Type `/console scriptErrors 1` in the chat and reload the game. If an error window appears, write here the first message (labelled 1/Many) that appeared.
No bugs

**Comment by Tuller** [comment]
I've not reproduced this one yet.

**Comment by nacedos** [comment]
Magically fixed itself, guess I was an update behind and something broke (?). Either way fixed now
