### ISSUE TITLE
Missing cd timers

### ISSUE THREAD

**Issue by britziboy** [tullamods/OmniCC#336]
I miss the cd timers on omnibar dont know why
![B213F789-8759-4235-A7DE-F4BF30AC5B4D](https://user-images.githubusercontent.com/70173495/91096736-d00c4200-e65e-11ea-951f-b36c56ede871.jpeg)

**Comment by Tuller** [comment]
I don't see OmniCC in the addons menu there.

**Comment by britziboy** [comment]
I need omnicc too? Its not okay without omnicc to show the cd timers?

**Comment by Tuller** [comment]
OmniBar isn't related to OmniCC, so I'm not sure. You could try enabling the Show Numbers for Cooldowns option in Interface Options.
