### ISSUE TITLE
Different sized icons

### ISSUE THREAD

**Issue by barnowl12312312** [tullamods/OmniCC#337]
**Running Software (issues missing this information will be deleted):**
 - Addon version: 8.3.6

 **Have you read the changelog? (please don't waste our time)**
yes

**Describe the bug**
Some icons appear larger than others

**Screenshots**
![WoWScrnShot_082620_211500](https://user-images.githubusercontent.com/70307642/91383680-9a439680-e7e1-11ea-953a-e6de6514f3e8.jpg)

**Comment by Tuller** [comment]
I've not replicated this one so far. Can you do so with just OmniCC + the standard UI?

**Comment by barnowl12312312** [comment]
So it looks like the issue is coming from "Blizzard Raid Frames - Bigger Buffs"
