### ISSUE TITLE
Problems of the translation

### ISSUE THREAD

**Issue by kitekingw** [tullamods/OmniCC#342]
OmniCC\config\themes.lua, line 460: name = 'Preview,'
The 'Preview' cannot be translated in the other language interfaces.

OmniCC\config\localization\zhCN.lua, it has lot of omissions and errors
Based on ''enUS.lua'' , I translated it into Chinese, and want to offer it to you. What should I do?

**Comment by Tuller** [comment]
I've fixed the missing entry for Preview. In the enUS its just an alias for the global  of PREVIEW which should be correct for all languages.

As far as translation goes, you can fork the project and create a pull request and apply your changes, or send me a link to the file that I can go over and merge in.

**Comment by kitekingw** [comment]
I have submitted it

**Comment by Tuller** [comment]
Thank you, I've merged the changes in. You should see them in the next release.
