### ISSUE TITLE
Can't disable cooldown finish effect

### ISSUE THREAD

**Issue by DPattee** [tullamods/OmniCC#349]
I've disabled all add-ons except:
- OmniCC 9.0.5
- Bartender 4.10.6
- Addon Control Panel

Testing with the druid Skull Bash ability since it has a relatively short 15 second cooldown

For testing purposes set the "finish effect = none" and "minimum cooldown duration = 0" on both the Default and Ignore themes.

When the countdown finishes the button still does a spark

**Comment by Tuller** [comment]
So that's not actually a finish effect, but part of the standard cooldown itself. We don't mess with it in OmniCC.
