### ISSUE TITLE
OmniCC not working on main Buffs Frame

### ISSUE THREAD

**Issue by JHalson** [tullamods/OmniCC#350]
**Give us a clear and concise description of the problem, and what you expect to happen**

OmniCC works on all UI elements it's expected to (unit frames, action bars) _except_ on the main player buffs frame on the top right. The bug occurs with no other addons loaded and with a fresh install of OmniCC with no changes made to settings. 
![image](https://user-images.githubusercontent.com/54885408/107165507-16562300-69ab-11eb-994b-e00e8f9a91ae.png)
Using Rules for 'buff' does not apply the default profile even though `/fstack` confirms this frame is the `BuffFrame`. I have also tried modifying the thresholds for size and duration to trigger OmniCC's overlay.

**Do you have any steps to reproduce this issue?**

No. it appears to be unique to my install. 

**Are you getting any error messages?**

None, after trying activating long buffs, short buffs, cancelling buffs after doing `/console scriptErrors 1` and `\reload`. No errors are reported.

**What version of OmniCC are you running?**

9.0.5 (latest at time of report)

**What version of World of Warcraft are you on?**

Wow Classic.
```
Dump: value=GetBuildInfo()
[1]="1.13.6",
[2]="36935",
[3]="Dec 11 2020",
[4]=11306
```

**What other addons are you running?**
None at the stage of issue reproduction. A list of installed (but disabled) Addons (generated via `dir \b` in the `\World of Warcraft\_classic_\Interface\AddOns` folder) is (apologies for the long list)
```
!Swatter
+Wowhead_Looter
Ace3
AceGUI-3.0_SFX-Widgets
AdvancedInterfaceOptions
Armory
Atlas
AtlasLootClassic
AtlasLootClassic_Collections
AtlasLootClassic_Crafting
AtlasLootClassic_Data
AtlasLootClassic_DungeonsAndRaids
AtlasLootClassic_Factions
AtlasLootClassic_Maps
AtlasLootClassic_Options
AtlasLootClassic_PvP
Atlas_ClassicWoW
Auc-Advanced
Auc-Filter-Basic
Auc-ScanData
Auc-Stat-Histogram
Auc-Stat-iLevel
Auc-Stat-Purchased
Auc-Stat-Simple
Auc-Stat-StdDev
Auc-Util-FixAH
Auctionator
BagBrother
Bagnon
Bagnon_Config
Bagnon_GuildBank
Bagnon_VoidStorage
Bartender4
BeanCounter
CensusPlusClassic
CharacterStatsClassic
ClassicAuraDurations
ClassicCastbars
ClassicCastbars_Options
DBM-AQ20
DBM-AQ40
DBM-Azeroth
DBM-BWL
DBM-Core
DBM-DefaultSkin
DBM-GUI
DBM-MC
DBM-Naxx
DBM-Onyxia
DBM-Party-Classic
DBM-StatusBarTimers
DBM-ZG
Details
Details_DataStorage
Details_Streamer
Details_TinyThreat
Dominos
Dominos_Cast
Dominos_Config
Dominos_Encounter
Dominos_Progress
Dominos_Roll
eAlignClassic
Enchantrix
Enchantrix-Barker
FishingBuddy
GatherMate2
GatherMate2_Data
GSE
GSE_GUI
GSE_LDB
HandyNotes
HandyNotes_Guild
HandyNotes_NPCs (Classic)
HandyNotes_TravelGuide (Classic)
HandyNotes_WorldMapButton
HealBot
HealBot_br
HealBot_cn
HealBot_Data
HealBot_de
HealBot_en
HealBot_es
HealBot_ExtraSkins
HealBot_fr
HealBot_gr
HealBot_hu
HealBot_it
HealBot_kr
HealBot_Options
HealBot_ru
HealBot_Tips
HealBot_tw
honorspy
IceHUD
IceHUD_Options
InFlight
InFlight_Load
Informant
ItemRack
ItemRackOptions
Kui_Media
Kui_Nameplates
Kui_Nameplates_Core
Kui_Nameplates_Core_Config
LargerMacroIconSelection
LargerMacroIconSelectionData
Leatrix_Maps
Leatrix_Plus
LibClassicDurations
LibClassicItemSets-1.0
LibClassicMobHealth-1.0
LibClassicSpellActionCount-1.0
LibStub
LinkSpellsClassic
Masque
Masque_Apathy
Masque_Caith
Masque_Cirque
Masque_Entropy
Masque_Epix
Masque_Qhil
Masque_Raeli
Masque_Serenity
NauticusClassic
Notepad
NovaInstanceTracker
OmniCC
OmniCC_Config
PallyPower
Prat-3.0
Prat-3.0_Libraries
Quartz
Questie
RingMenu
SexyMap
Skillet-Classic
SlashFour
SlideBar
Stubby
TargetHealth
TellMeWhen
TellMeWhen_Options
TitanClassic
TitanClassicAmmo
TitanClassicBag
TitanClassicClock
TitanClassicGold
TitanClassicLocation
TitanClassicLootType
TitanClassicPerformance
TitanClassicRegen
TitanClassicRepair
TitanClassicVolume
TitanClassicXP
TomPoints
TomTom
WeaponSwingTimer
WhatsTraining
whoaBlueShamans
WIM
WowheadQuickLink
ZPerl
ZPerl_ArcaneBar
ZPerl_CustomHighlight
ZPerl_Options
ZPerl_Party
ZPerl_PartyPet
ZPerl_Player
ZPerl_PlayerBuffs
ZPerl_PlayerPet
ZPerl_RaidAdmin
ZPerl_RaidFrames
ZPerl_RaidHelper
ZPerl_RaidMonitor
ZPerl_RaidPets
ZPerl_Target
ZPerl_TargetTarget
```
I believe the issue may  be to do with either Zperl, Titan Panel, or Leatrix Plus, since these are the addons that interact with buffs.

**Comment by Tuller** [comment]
This one is expected, as the buff frame does not implement cooldown displays for those buffs. If they did, omnicc would show timers

**Comment by JHalson** [comment]
Thank you for responding :) I see - Are there other buffs I could try acquiring to see if it is working as you expect? I remember at some point it was working for world buffs (Cry of the Dragonslayer) but now it does not. It may have been that another mod (ClassicAuraDurations?) was adding those. Although I have also tried configuring that mod with no effect.

**Comment by Tuller** [comment]
I don't know of one offhand, unfortunately.
