### ISSUE TITLE
CD Text not showing in WeakAura

### ISSUE THREAD

**Issue by jaycrae** [tullamods/OmniCC#351]
**Give us a clear and concise description of the problem, and what you expect to happen**

Starting around Feb 1, I noticed that OmniCC cooldown text stopped working on my WeakAuras (Afenar Shadow Priest WA to be specific). It was working perfectly the day before, but then all of the sudden it didn't want to show.

To troubleshoot I reinstalled OmniCC addon and even removed and reinstalled the WA, but alas the problem persisted. 

**Do you have any steps to reproduce this issue?**

As of today, Feb 10, I still cannot get the OmniCC CD text to appear.

**Are you getting any error messages?**

No errors that I can see

**What version of OmniCC are you running?**

[17:31] You are using OmniCC Version (9.0.5)

**What version of World of Warcraft are you on?**

9.0.2

**What other addons are you running?**
ElvUI
Addonskins
Shadow & Light
Angry Keystones
BattleGroundEnemies
BugGrabber/BugSack
DBM
Details
KUI
LoggerHead
MDT
OmniCC
Pawn
Premade Group Filter
RaiderIO
RareScanner
RLootCouncil
Right Click Modifier
Shared Media
SimC
TomTom
WeakAuras

**Comment by Tuller** [comment]
Have you adjusted anything in WA recently? I know there are settings there to use OmniCC versus not.

**Comment by jaycrae** [comment]
I have not. It was super weird, It was working in the AM, but then that evening it stopped working. I did not change anything.
