### ISSUE TITLE
Cooldown Spiral Alpha

### ISSUE THREAD

**Issue by Natlyz** [tullamods/OmniCC#352]
**Hello!**

Would be nice to have an option to adjust the cooldown spiral's transparency, so the spell/buff/debuff under it is easier to see.

**Thanks 😊**

**Comment by Tuller** [comment]
I'll need to play around with Cooldown:SetAlpha again. It appears to work again, but had issues in the past. Right now, there's the Draw cooldown swipes option to completely hide it.

**Comment by Natlyz** [comment]
Hope it works, don't really want to remove the spiral completely.

**Comment by Tuller** [comment]
It seems to work fine, and is now in the latest beta release.

**Comment by Natlyz** [comment]
Finally we'll get this option! Thanks a lot 😊

**Comment by Natlyz** [comment]
I've tested it a bit today and so far it seems to be working great. I've set it to around 60% and it's much easier to see the spell/buff/debuff icons now and still see the spiral.

**Comment by Natlyz** [comment]
After several days of testing I've encountered no bugs.

**Comment by Tuller** [comment]
Yeah, I'm pushing it out as a release today
