### ISSUE TITLE
Auto Reset Blizzard's Cooldown Text Option

### ISSUE THREAD

**Issue by yvx5166** [tullamods/OmniCC#354]
**Give us a clear and concise description of the problem, and what you expect to happen**

I installed OmniCC b/c of the ability cooldown alerts. Yet, OmniCC resets the option of the Blizzard cooldown text option in the Interface tab. Once I have enabled the CD text option and reload my UI, it automatically reset it to off. Is there a way to change it for not resetting the Blizzard CD option? 

**Do you have any steps to reproduce this issue?**

I have tested with ElvUI built-in lua error test mode, and re-enable each addon 1-by-1. Once I enabled OmniCC addon, the option resets from ON to OFF. 
**Are you getting any error messages?**

No error message

**What version of OmniCC are you running?**

9.0.5
**What version of World of Warcraft are you on?**

9.0.2

**What other addons are you running?**

I'm running a lot of addons, but about the CD part, only ElvUI and OmniCC

**Comment by Tuller** [comment]
You're not meant to use blizzard cooldown count if using Omnicc - they both so the same job.

**Comment by yvx5166** [comment]
Yes, I understand that. But the main reason I use OmniCC is to use the CD glow function that included. I disable the OmniCC CD text  in the addon to prevent duplicate CD text from both ElvUI and OmniCC. So I wonder If I turned off the OmniCC CD text in the addon can prevent auto-reset the blizzard CD text settings?

**Comment by Tuller** [comment]
I've added a new flag in 9.0.7. Try `/run OmniCC.db.global.disableBlizzardCooldownText = false; ReloadUI()`
