### ISSUE TITLE
Not getting timers with this error

### ISSUE THREAD

**Issue by Pomptime** [tullamods/OmniCC#356]
Hello. I'm new to github and issues reporting, but it seems that AddOn is not working correctly for me. Timers do not show, and i keep getting this error.

Date: 2021-03-07 04:41:04
ID: 1
Error occured in: Global
Count: 1
Message: ..\AddOns\OmniCC\settings\settings.lua line 147:
   attempt to compare nil with number
Debug:
   OmniCC\settings\settings.lua:147: UpgradeDB()
   OmniCC\settings\settings.lua:15: InitializeDB()
   OmniCC\main.lua:67: func()
   OmniCC\main.lua:16:
      OmniCC\main.lua:13
Locals:
self = <table> {
 PLAYER_LOGOUT = <function> defined @Interface\AddOns\OmniCC\main.lua:83
 AddRule = <function> defined @Interface\AddOns\OmniCC\settings\rules.lua:5
 PLAYER_ENTERING_WORLD = <function> defined @Interface\AddOns\OmniCC\main.lua:71
 OnNewProfile = <function> defined @Interface\AddOns\OmniCC\settings\settings.lua:19
 MigrateDrawSwipesSetting = <function> defined @Interface\AddOns\OmniCC\settings\settings.lua:221
 HasRule = <function> defined @Interface\AddOns\OmniCC\settings\rules.lua:78
 CreateHiddenFrame = <function> defined @Interface\AddOns\OmniCC\main.lua:114
 AddTheme = <function> defined @Interface\AddOns\OmniCC\settings\themes.lua:6
 OnProfileChanged = <function> defined @Interface\AddOns\OmniCC\settings\settings.lua:28
 OnProfileReset = <function> defined @Interface\AddOns\OmniCC\settings\settings.lua:23
 UpgradeDB = <function> defined @Interface\AddOns\OmniCC\settings\settings.lua:139
 NumRulesets = <function> defined @Interface\AddOns\OmniCC\settings\rules.lua:94
 Cooldown = <table> {
 }
 GetDefaultTheme = <function> defined @Interface\AddOns\OmniCC\settings\themes.lua:59
 AddDefaultRulesets = <function> defined @Interface\AddOns\OmniCC\settings\settings.lua:116
 ADDON_LOADED = <function> defined @Interface\AddOns\OmniCC\main.lua:60
 PLAYER_LOGIN = <function> defined @Interface\AddOns\OmniCC\main.lua:75
 GetDefaultThemeID = <function> defined @Interface\AddOns\OmniCC\settings\themes.lua:55
 GetMatchingRule = <function> defined @Interface\AddOns\OmniCC\settings\rules.lua:115
 SetRulePriority = <function> defined @Interface\AddOns\OmniCC\settings\rules.lua:46
 GetThemes = <function> defined @Interface\AddOns\OmniCC\settings\themes.lua:63
 db = <table> {
 }
 GetActiveRulesets = <function> defined @Interface\AddOns\OmniCC\settings\rules.lua:110
 GetRulesets = <function> defined @Interface\AddOns\OmniCC\settings\rules.lua:90
 ReorderRules = <function> defined @Interface\AddOns\OmniCC\settings\rules.lua:68
 InitializeDB = <function> defined @Interface\AddOns\OmniCC\settings\settings.lua:8
 IsConfigAddonEnabled = <function> defined @Interface\AddOns\OmniCC\main.lua:106
 Display = <unnamed> {
 }
 RemoveRule = <function> defined @Interface\AddOns\OmniCC\settings\rules.lua:31
 FX = <table> {
 }
 RemoveTheme = <function> defined @Interface\AddOns\OmniCC\settings\themes.lua:23
 ShowOptionsFrame = <function> defined @Interface\AddOns\OmniCC\main.lua:93
 HasTheme = <function> defined @Interface\AddOns\OmniCC\settings\themes.lua:51
 GetTheme = <function> defined @Interface\AddOns\OmniCC\settings\themes.lua:43
 MigrateLegacySettings = <function> defined @Interface\AddOns\OmniCC\settings\settings.lua:160
 Timer = <table> {
 }
 frame = <unnamed> {
 }
 GetButtonIcon = <function> defined @Interface\AddOns\OmniCC\main.lua:122
 GetDBDefaults = <function> defined @Interface\AddOns\OmniCC\settings\settings.lua:32
}
dbVersion = nil
(*temporary) = <function> defined @Interface\AddOns\OmniCC\settings\settings.lua:160
(*temporary) = <table> {
 PLAYER_LOGOUT = <function> defined @Interface\AddOns\OmniCC\main.lua:83
 AddRule = <function> defined @Interface\AddOns\OmniCC\settings\rules.lua:5
 PLAYER_ENTERING_WORLD = <function> defined @Interface\AddOns\OmniCC\main.lua:71
 OnNewProfile = <function> defined @Interface\AddOns\OmniCC\settings\settings.lua:19
 MigrateDrawSwipesSetting = <function> defined @Interface\AddOns\OmniCC\settings\settings.lua:221
 HasRule = <function> defined @Interface\AddOns\OmniCC\settings\rules.lua:78
 CreateHiddenFrame = <function> defined @Interface\AddOns\OmniCC\main.lua:114
 AddTheme = <function> defined @Interface\AddOns\OmniCC\settings\themes.lua:6
 OnProfileChanged = <function> defined @Interface\AddOns\OmniCC\settings\settings.lua:28
 OnProfileReset = <function> defined @Interface\AddOns\OmniCC\settings\settings.lua:23
 UpgradeDB = <function> defined @Interface\AddOns\OmniCC\settings\settings.lua:139
 NumRulesets = <function> defined @Interface\AddOns\OmniCC\settings\rules.lua:94
 Cooldown = <table> {
 }
 GetDefaultTheme = <function> defined @Interface\AddOns\OmniCC\settings\themes.lua:59
 Add
AddOns:
  Swatter, v8.2.6377 (SwimmingSeadragon)
  AtlasLootClassic, vv1.5.8
  AtlasLootClassicData, vv1.5.8
  AtlasLootClassicDungeonsAndRaids, vv1.5.8
  AucAdvanced, v8.2.6430 (SwimmingSeadragon)
  AucFilterBasic, v8.2.6364 (SwimmingSeadragon)
  AucStatHistogram, v8.2.6366 (SwimmingSeadragon)
  AucStatiLevel, v8.2.6370 (SwimmingSeadragon)
  AucStatPurchased, v8.2.6367 (SwimmingSeadragon)
  AucStatSimple, v8.2.6399 (SwimmingSeadragon)
  AucStatStdDev, v8.2.6369 (SwimmingSeadragon)
  AucUtilFixAH, v8.2.6371 (SwimmingSeadragon)
  BagBrother, v
  BagFreeSpaceCounter, v1.0.4
  Bagnon, v9.0.5
  BeanCounter, v8.2.6434 (SwimmingSeadragon)
  BiSTracker, v3.3
  ClassicAuraDurations, v1.13.61
  ClassicCastbars, vv1.3.20
  ClassicCastbarsOptions, vv1.3.20
  ClassicCodex, v1.2.3
  Enchantrix, v8.2.6428 (SwimmingSeadragon)
  EnchantrixBarker, v8.2.6469 (SwimmingSeadragon)
  EZJunk, v1.0.1
  FasterLooting, v1.1.2
  FishingBuddy, v0.7.3 Beta 7
  FiveSecondRule, v1.1
  LeatrixMaps, v1.13.95
  LeatrixPlus, v1.13.95
  ModernAlternatePowerBar, v1.0
  OmniCC, v@project-version@
  Stubby, v8.2.6376 (SwimmingSeadragon)
  BlizRuntimeLib_ruRU v1.13.6.11306 <none>
  (ck=47f)

**Comment by Pomptime** [comment]
Here is another log, with everything except OmniCC and Swatter disabled.

Date: 2021-03-07 06:32:31
ID: 1
Error occured in: Global
Count: 1
Message: ..\AddOns\OmniCC\settings\settings.lua line 147:
   attempt to compare nil with number
Debug:
   OmniCC\settings\settings.lua:147: UpgradeDB()
   OmniCC\settings\settings.lua:15: InitializeDB()
   OmniCC\main.lua:67: func()
   OmniCC\main.lua:16:
      OmniCC\main.lua:13
Locals:
self = <table> {
 PLAYER_LOGOUT = <function> defined @Interface\AddOns\OmniCC\main.lua:83
 AddRule = <function> defined @Interface\AddOns\OmniCC\settings\rules.lua:5
 PLAYER_ENTERING_WORLD = <function> defined @Interface\AddOns\OmniCC\main.lua:71
 OnNewProfile = <function> defined @Interface\AddOns\OmniCC\settings\settings.lua:19
 MigrateDrawSwipesSetting = <function> defined @Interface\AddOns\OmniCC\settings\settings.lua:221
 HasRule = <function> defined @Interface\AddOns\OmniCC\settings\rules.lua:78
 CreateHiddenFrame = <function> defined @Interface\AddOns\OmniCC\main.lua:114
 AddTheme = <function> defined @Interface\AddOns\OmniCC\settings\themes.lua:6
 OnProfileChanged = <function> defined @Interface\AddOns\OmniCC\settings\settings.lua:28
 OnProfileReset = <function> defined @Interface\AddOns\OmniCC\settings\settings.lua:23
 UpgradeDB = <function> defined @Interface\AddOns\OmniCC\settings\settings.lua:139
 NumRulesets = <function> defined @Interface\AddOns\OmniCC\settings\rules.lua:94
 Cooldown = <table> {
 }
 GetDefaultTheme = <function> defined @Interface\AddOns\OmniCC\settings\themes.lua:59
 AddDefaultRulesets = <function> defined @Interface\AddOns\OmniCC\settings\settings.lua:116
 ADDON_LOADED = <function> defined @Interface\AddOns\OmniCC\main.lua:60
 PLAYER_LOGIN = <function> defined @Interface\AddOns\OmniCC\main.lua:75
 GetDefaultThemeID = <function> defined @Interface\AddOns\OmniCC\settings\themes.lua:55
 GetMatchingRule = <function> defined @Interface\AddOns\OmniCC\settings\rules.lua:115
 SetRulePriority = <function> defined @Interface\AddOns\OmniCC\settings\rules.lua:46
 GetThemes = <function> defined @Interface\AddOns\OmniCC\settings\themes.lua:63
 db = <table> {
 }
 GetActiveRulesets = <function> defined @Interface\AddOns\OmniCC\settings\rules.lua:110
 GetRulesets = <function> defined @Interface\AddOns\OmniCC\settings\rules.lua:90
 ReorderRules = <function> defined @Interface\AddOns\OmniCC\settings\rules.lua:68
 InitializeDB = <function> defined @Interface\AddOns\OmniCC\settings\settings.lua:8
 IsConfigAddonEnabled = <function> defined @Interface\AddOns\OmniCC\main.lua:106
 Display = <unnamed> {
 }
 RemoveRule = <function> defined @Interface\AddOns\OmniCC\settings\rules.lua:31
 FX = <table> {
 }
 RemoveTheme = <function> defined @Interface\AddOns\OmniCC\settings\themes.lua:23
 ShowOptionsFrame = <function> defined @Interface\AddOns\OmniCC\main.lua:93
 HasTheme = <function> defined @Interface\AddOns\OmniCC\settings\themes.lua:51
 GetTheme = <function> defined @Interface\AddOns\OmniCC\settings\themes.lua:43
 MigrateLegacySettings = <function> defined @Interface\AddOns\OmniCC\settings\settings.lua:160
 Timer = <table> {
 }
 frame = <unnamed> {
 }
 GetButtonIcon = <function> defined @Interface\AddOns\OmniCC\main.lua:122
 GetDBDefaults = <function> defined @Interface\AddOns\OmniCC\settings\settings.lua:32
}
dbVersion = nil
(*temporary) = <function> defined @Interface\AddOns\OmniCC\settings\settings.lua:160
(*temporary) = <table> {
 PLAYER_LOGOUT = <function> defined @Interface\AddOns\OmniCC\main.lua:83
 AddRule = <function> defined @Interface\AddOns\OmniCC\settings\rules.lua:5
 PLAYER_ENTERING_WORLD = <function> defined @Interface\AddOns\OmniCC\main.lua:71
 OnNewProfile = <function> defined @Interface\AddOns\OmniCC\settings\settings.lua:19
 MigrateDrawSwipesSetting = <function> defined @Interface\AddOns\OmniCC\settings\settings.lua:221
 HasRule = <function> defined @Interface\AddOns\OmniCC\settings\rules.lua:78
 CreateHiddenFrame = <function> defined @Interface\AddOns\OmniCC\main.lua:114
 AddTheme = <function> defined @Interface\AddOns\OmniCC\settings\themes.lua:6
 OnProfileChanged = <function> defined @Interface\AddOns\OmniCC\settings\settings.lua:28
 OnProfileReset = <function> defined @Interface\AddOns\OmniCC\settings\settings.lua:23
 UpgradeDB = <function> defined @Interface\AddOns\OmniCC\settings\settings.lua:139
 NumRulesets = <function> defined @Interface\AddOns\OmniCC\settings\rules.lua:94
 Cooldown = <table> {
 }
 GetDefaultTheme = <function> defined @Interface\AddOns\OmniCC\settings\themes.lua:59
 Add
AddOns:
  Swatter, v8.2.6377 (SwimmingSeadragon)
  OmniCC, v9.0.6
  BlizRuntimeLib_ruRU v1.13.6.11306 <none>
  (ck=65)

**Comment by Tuller** [comment]
This should be fixed in 9.0.7
