### ISSUE TITLE
Reattach to blizzard group frame?

### ISSUE THREAD

**Issue by weishiuchang** [tullamods/OmniCC#367]
**Is your feature request related to a problem? Please describe.**
I run OmniCC with vuhdo for my druid healing in dungeons. I don't raid often, and when I do I don't much care about people's CDs. However, when I am in a 5 man group, I would like OmniCC to be attached to the regular Blizzard group frame instead of attaching to vuhdo. I cannot seem to find an option in OmniCC to achieve this. The closest I can find is a manual placement of OmniCC -- I would rather not have to manually move OmniCD back up to the Blizzard group frame if I don't have to.

**Describe the solution you'd like**
If there is an option that I have missed, a simple checkbox that says "do not attach to plugin frames", please point me to it. Otherwise, I would like to request an option to do so.

**Describe alternatives you've considered**
Manual placement of OmniCC frame. Seems excessive when it already normally attaches to the blizzard group frame with I have vuhdo disabled.

**Additional context**
I'm really hoping it's an option that exists already and I am just blind to the description.

**Comment by Tuller** [comment]
Do you have a screenshot of what you mean here?

**Comment by weishiuchang** [comment]
Yes, of course. Here's a screen shot of omnicd (test mode) attached to the vuhdo frame:
![omnicd_with_vuhdo](https://user-images.githubusercontent.com/43444925/119581001-93ba6d80-bdb9-11eb-81d7-3e2b8392f1df.png)

And here's what I'm looking for with omnicd in a dungeon:
![omnicd_dungeon](https://user-images.githubusercontent.com/43444925/119581027-a6cd3d80-bdb9-11eb-8d03-b23b6f8cdc29.png)

**Comment by Tuller** [comment]
OmniCD is a different addon :)

**Comment by weishiuchang** [comment]
Ahhh... My bad. That will teach me to search for the addon in the middle of the night. Thanks!
