### ISSUE TITLE
Cooldowns not appearing on FocusFrames

### ISSUE THREAD

**Issue by dbarfield** [tullamods/OmniCC#368]
**Give us a clear and concise description of the problem, and what you expect to happen**
Created a focus frame (for Polymorph) using /focus command ... entered /script message(GetMouseFocus():GetName() to get the type of frame .. it returned "FocusFrame"

Went into settings of OmniCC, rules, enabled "Unit Nameplates" and added FocusFrame on a new line into "Patterns" field. accepted, hit okay.

Cast polymorph and countdown appeared on unit frame but not on FocusFrame as I had specified.

OmnicCC and WoW versions
You are using OmniCC Version (9.0.10)
Dump: value=GetBuildInfo()
[1]="2.5.1",
[2]="38921",
[3]="Jun  4 2021",
[4]=20501

**What other addons are you running?**
Lots ... are there any particular ones that clash ?

**Comment by Tuller** [comment]
Have you adjusted the minimum size slider? Do you see cooldown spirals on the buffs/debuffs normally?

**Comment by dbarfield** [comment]
Sliders are still set as default "Resize cooldown text to fit withing frames"

OmniCC shows cooldowns for abilities on bar and things like polymorh / banish countdowns on mobs formally.

**Comment by Tuller** [comment]
Being that this is classic, I don’t think we’re yet in an era where buffs/debuts normally present this information

**Comment by dbarfield** [comment]
So adding "FocusFrame" to patterns for "Unit Nameplates" is not supported ?

**Comment by Tuller** [comment]
For OmniCC to display text, you need to be able to see a cooldown spiral on the buff/debuff. You might need something like ClassicAuraDurations for the focus frame https://www.curseforge.com/wow/addons/classicauradurations

**Comment by dbarfield** [comment]
I will try that .. thank you.
