### ISSUE TITLE
Duration not appearing on PetFrame

### ISSUE THREAD

**Issue by rulezxy** [tullamods/OmniCC#369]
Hello,

seems that Petframe debuff-duration/timer and shadows are missing.

Example: https://imgur.com/a/z9gNeYW

Is there a way to fix this?

Ty

**Comment by Tuller** [comment]
I don't see a cooldown spiral on those icons, so that's likely why you're not getting information from OmniCC

**Comment by rulezxy** [comment]
Sorry, 

I see its not a bug. 

But is it still possible to include Pet-De/buffs for future updates without having to mess around with the code much?

I am unsure about PetFrameBuffs since I never changed something related.
