### ISSUE TITLE
Old Aura CD`s is not shown

### ISSUE THREAD

**Issue by BigBont** [tullamods/OmniCC#374]
Retail v. 9.1
When you login and check the ''Old'' Aura CD`s (I mean yesterday, the day before yesterday, etc) they are not displayed.

Green circles - work well, I get this buffs today.
Red circles - do not show CD's (it's ShadowedUnitFrame + OmniCC ) I get this buffs yesterday, Rune it`s 3 days ago
https://snipboard.io/MxpD3n.jpg

**Comment by Tuller** [comment]
This should be resolved. If not, check the maximum duration slider and set it to zero.

**Comment by BigBont** [comment]
No, it`s not =(((
