### ISSUE TITLE
X/Y-axis softMax values

### ISSUE THREAD

**Issue by XyzKangUI** [tullamods/OmniCC#379]
**Describe the solution you'd like**
Could you change the X-axis softMax to 50 or higher? This adds more possibilities of customizing addons to have the timer next to the icon, e.g. Afflicted style OmniBar. 

`x = {
                        order = 2,
                        type = 'range',
                        name = L.HorizontalOffset,
                        softMin = -18,
                        softMax = 50,
                        step = 1,
                        get = function()
                            return theme.xOff
                        end,
                        set = function(_, val)
                            theme.xOff = val
                            OmniCC.Display:ForAll('UpdateCooldownTextPositionSizeAndColor')
                        end
                    },`

Thank you in advance.

**Comment by Tuller** [comment]
You should be able to type in a number beyond the soft max
