### ISSUE TITLE
hi sorry not really feature request 

### ISSUE THREAD

**Issue by blecaplol** [tullamods/OmniCC#380]
but is there anywhere I could ask for help from anyone? like a discord or something dedicated? having a trouble identifying omniCD icons to stop omniCC from tracking. sorry for this but i cant find anywhere to ask.

**Comment by Tuller** [comment]
Pretty much here.

I think OmniCD names all of their stuff OmniCDSomething. So you should be able to just add a rule with the pattern OmniCD and assign a theme to that.
