### ISSUE TITLE
Disable CD text for individual charges of a multi-use ability?

### ISSUE THREAD

**Issue by SuttonX** [tullamods/OmniCC#383]
Sorry for asking here but I wasn't able to find a link to a Discord or anything.

Basically I love OmniCC and have it set up how I want, aside from one thing - when an ability has multiple charges, I don't want to see ANY CD text on that ability until ALL charges are exhausted.  Currently I get a (smaller) CD in between each charge, and then the regular one after I use the remaining charges.  Personally those in-between ones throw me off cause when I see any CD numbers there, I think all the charges are gone.  I'd prefer no text at all until I literally can't cast the ability any more - I have a small border that fills around it to show me when the next charge will be back, so the charge text isn't needed for me personally.

I know it's a personal problem, just curious if you could tell me what to modify in what file to only block CDs for individual charges and nothing else.

Example - Crusader Strike on Paladin after you rank it up and get 2 charges.  The whole time I was leveling I had the one charge so got used to the CD there, so now when I still have that second charge left, in my head I think I don't cause I'm seeing those (slightly smaller) CD numbers there for the first charge so I'm thinking the entire thing is on CD.  I understand the charge text is slightly smaller and a different color, but I would prefer just no text at all until every charge is exhausted.

If you could add a toggle box for "CD Text for Individual Charges?" in the addon options in the Interface screen, that would be amazing.  Or again, just tell me personally what to modify in my PC files to suppress those.  Thanks in advace!

**Comment by Tuller** [comment]
Try making the charge cooldown color transparent

**Comment by SuttonX** [comment]
I don't see where to do that, please excuse my ignorance. I'm not in front of the computer at the moment though but I don't remember seeing anything for it

**Comment by Tuller** [comment]
It would be in the same spot where you modify other colors for other duration thresholds, like soon to expire.

**Comment by SuttonX** [comment]
Just got home and hopped on, found it under the colors section, "Restoring
Charges" - clicked on the color and then slid the alpha slider (right side)
all the way down to 0 and saved.

That did the trick! Perfect, thanks! Sorry to bother
