### ISSUE TITLE
Cooldown/Buff/Debuff remining timers not appearing on DF default Buff and Debuff frames

### ISSUE THREAD

**Issue by Mythris29** [tullamods/OmniCC#402]
There aren't any omnicc cooldown numbers appearing on the dragonflight default buff/debuff frames

OmniCC 10.0.1

Wow version 10.0.2

**Comment by Mythris29** [comment]
Just wanted to see if there is anything I can do to help (log gathering etc.)

**Comment by Tuller** [comment]
So there's not anything to do for this one really, the default UI doesn't show cooldown spirals on buffs/debuffs.

**Comment by Mythris29** [comment]
Ah I didn't realize that. That's too bad since it's really the only thing keeping me from using the default UI with just OmniCC for my unit frames. Thank you for responding and hopefully blizzard changes it's behavior in the future.
