### ISSUE TITLE
All CD timers (text + overlay) and keybinds disappear from BLIZZ actionbars

### ISSUE THREAD

**Issue by ghost** [tullamods/OmniCC#407]
**Give us a clear and concise description of the problem, and what you expect to happen**

Sometimes all my CD timers (text + overlay) and keybinds disappear from my BLIZZ actionbars. 

Screenshots can help quite a bit.

I dont have one rn but its easy to envision. Everything is just blank from keybinds all of a sudden and even if I press a CD it doesnt start to countdown in any way shape or form. I can basically see no CDs. Its just tooltips of the spells. The only way to fix it is to /reload but that looses me the arena game.

**Do you have any steps to reproduce this issue?**

No. I can reproduce it by playing for a while and letting it happen again but I dont know exactly how and why it happens.

The best way for us to fix an issue is to know how to reproduce it.

**Are you getting any error messages?**

Yes in chat. "Cant do that because of Omnicc" or w/e it says.

World of Warcraft disables errors by default. Install [BugSack](https://www.curseforge.com/wow/addons/bugsack) or addon error messages via `/console scriptErrors 1` and reload the game. If an error window appears, write here the first message (labelled 1/Many) that appeared. If you're getting especially low FPS, it probably means that you're getting a bunch of errors that are hidden.

**What version of OmniCC are you running?**

Newest.

You can get this via the slash command `/omnicc version`. If you're not running the latest release, please try that version first.

**What version of World of Warcraft are you on?**

Latest.

You can get this via the command, `/dump GetBuildInfo()`.

**What other addons are you running?**

Ability Team Tracker
Arena Nameplate Numbers BFA
ArenaMarker
BigDebuffs
Details! Damage Meter
Frame Sort
HealthBarColor
Leatrix Plus
Omnibar
sArena Updated
Spell Alerter Classic
Threat Plates
Weakauras

Lot of times, OmniCC issues are AddOn specific.

**Comment by Tuller** [comment]
OmniCC has no impact on key binds, so I think the error is a different add-on.
