### ISSUE TITLE
Does not work for target in Era PTR Hardcore

### ISSUE THREAD

**Issue by DavidBabel** [tullamods/OmniCC#409]
**Give us a clear and concise description of the problem, and what you expect to happen**

OmniCC works for everything except target debuff, verified in Luna Unit Frame, but also in Blizzard frames
![image](https://github.com/tullamods/OmniCC/assets/5599375/f28b2a60-e5dc-47ce-a44d-aef84484f738)

**Do you have any steps to reproduce this issue?**

Connect to classic Era PTR Hardcore and try.

**Are you getting any error messages?**

no bug

**What version of OmniCC are you running?**

![image](https://github.com/tullamods/OmniCC/assets/5599375/fc15f234-fec2-4645-9bc9-f1ccac8849b3)

**What version of World of Warcraft are you on?**

![image](https://github.com/tullamods/OmniCC/assets/5599375/536bc2c5-816a-460e-ba8b-64800bd1f36e)

**What other addons are you running?**

From fresh install :
![image](https://github.com/tullamods/OmniCC/assets/5599375/25ca4440-8b7d-4f2c-b374-35fd7dce7788)
![image](https://github.com/tullamods/OmniCC/assets/5599375/60caa627-412f-4620-afbd-707b8a5f9dfc)

**Comment by Tuller** [comment]
Classic doesn't actually render cooldowns for target debuffs, so there's nothing for OmniCC to show text for.
