### ISSUE TITLE
OmniCC rules and Dominos actionbars

### ISSUE THREAD

**Issue by nonoash** [tullamods/OmniCC#410]
Hello, 

In Wow Classic, i have a problem with OmniCC rules and Dominos actionbars, the rule is only applies to the first Dominos actionbar using simply "ActionButton"
but I also tried ActionButton2 DominosFrame2 DominosActionButton2 Dominos, none worked. Any ideas on which is the correct pattern for other actionbars using dominos?
thanks

**Comment by Tuller** [comment]
Depending on the action bar you looking at, the frame you are looking at might not quite be the one you're looking for.  Try adding MultiBar as well
