### ISSUE TITLE
Interference With Setting / Cooldowns Not Visible In Certain Places

### ISSUE THREAD

**Issue by SleekSnake** [tullamods/OmniCC#425]
I am having an issue where my cooldowns are not showing in bags. I had checked the setting "Show Numbers for Cooldowns" which alleviates this problem. However, upon any sort of reload, the setting becomes unchecked again. The cooldowns for anything on my  Action Bars are working.

![issue 2](https://github.com/tullamods/OmniCC/assets/154693660/0e78b4e7-ec93-49c2-b4a0-c6ed33c8c61b)
![issue](https://github.com/tullamods/OmniCC/assets/154693660/c8ec0f8e-5668-4b66-87c6-20d35321576d)

Create a theme with "Display cooldown text" and "Resize cooldown text to fit within frames" both checked. Then, under Rules, I have Action Bars enabled with ActionButton and MultiBar as the Patterns. I also have Auras enabled with Aura, Buff, Debuff as the Patterns. I have Unit Nameplates unchecked. I have Plater Nameplates Rule checked, with PlaterMainAuraIcon, PlaterSecondaryAuraIcon and ExtraIconRowIcon as the Patterns.

I am not getting any error messages.

I am using OmniCC Version 10.2.4.

I am using Classic WoW SoD version 1.15.1 (53247) (x64).

I am running these addons: 

Auctionator // Bagnon // BetterFishing // BigDebuffs // ClassicAuraDurations // Details! // Dominos // ExtendedCharacterStats // 
Leatrix Plus // LFG Bulletin Board // MinimapButtonBag-Reborn // NugEnergy // Plater // Questie // Ranker // RestedXP Guides // Speedy AutoLoot // Spy // TacoTip // ThreatClassic2 // Tyllus' HideCastBar // WeaponSwingTimer // whoa BlueShamans.

---

While I am here, **I do apologize** if this is simply intended and these two settings are not meant to coexist. If it is _not_ intended to work this way, please do let me know how I can have OmniCC also apply to cooldowns everywhere (in my bags, or elsewhere). If it _is_ inteded to work this way, then would I simply disable my Action Bar Rule and then use the Blizzard setting to have them both work synergistically?

**Comment by Tuller** [comment]
So to confirm, you're attempting to use an allow list mode for OmniCC, right? That is, you've unchecked "Display Cooldown Text" from the default them, and then are applying a new theme on the particular elements you want to show text for? If so, then you'll want to create a rule for Bagnon and add `ContainerItem` as the pattern.

The "Show Numbers for Cooldowns" option in Action Bars enables Blizzard's implementation of cooldown count text. OmniCC unchecks the option automatically when the addon is loaded to prevent cooldowns from showing up twice.
