### ISSUE TITLE
icon and anchor blizzard party 123

### ISSUE THREAD

**Issue by blablax000** [tullamods/OmniCC#433]
Hello, I use omnicc to display the cc mainly of my mates in arena. I set the addon so that the anchor is linked to the party 1 or 2 or 3 and that the spell in question appears on the right of the group frame of the targeted player.
 The problem is that I've been using this addon for months and the icon for a current spell doesn't always appear next to the right group frame, which is quite confusing.
When I'm doing 3v3 and I'm leadder it seems to be the only condition where the addon works correctly, otherwise in shuffle mode it's completely random.

**Comment by Tuller** [comment]
I think you are referring you the OmniCD addon

**Comment by blablax000** [comment]
Yes, I must have been tired that day because it was losecontrol and not omnicc. Sorry
