### ISSUE TITLE
Larodar (Amirdrassil) encounter only Lua errors

### ISSUE THREAD

**Issue by AhoyThere** [tullamods/OmniCC#435]
Whenever I do the Larodar encounter in Amirdrassil I get bombarded with Lua errors. This happens only on Larodar but it does so for months now, I've just been to lazy to post about the issue here. This also means this happened across multiple WoW patches and OmniCC versions. But since OmniCC was updated today and I encountered these Lua errors again I finally overcame my lazyness and post about it.

Since you asking for steps to reproduce, well I can't tell you the steps. All I can say it always(!) happens for me at Larodar (only) and it happens across all my characters.

The versions of OmniCC I'm using today is 10.2.8
The version of my WoW client is 10.2.7 / 55165 / June 13 2024 / 100207
But as I already wrote, this happened in previous versions as well.

Buggrabber shows this:

11336x OmniCC/core/cooldown.lua:256: calling 'IsVisible' on bad self (Usage: local isVisible = self:IsVisible())
[string "=[C]"]: in function `IsVisible'
[string "@OmniCC/core/cooldown.lua"]:256: in function `UpdateText'
[string "@OmniCC/core/cooldown.lua"]:284: in function <OmniCC/core/cooldown.lua:282>
Locals:
Skipped (In Encounter)

and

26572x OmniCC/core/cooldown.lua:228: calling 'IsVisible' on bad self (Usage: local isVisible = self:IsVisible())
[string "=[C]"]: in function `IsVisible'
[string "@OmniCC/core/cooldown.lua"]:228: in function `UpdateText'
[string "@OmniCC/core/cooldown.lua"]:256: in function <OmniCC/core/cooldown.lua:254>
Locals:
Skipped (In Encounter)

And finally, here's the list of the AddOns I'm using:
!BugGrabber
BeQuiet
BetterWardrobe
BugSack
DBM
DejaCharacterStats
Details
EasyDelete
ErrorFilter
GTFO
HandyNotes
LFGMute
MapCoords
MogIt
Molinari
OmniCC
Pawn
PremadeGroupFilter
RaiderIO
RETabBinder
SavedInstaces
SimulationCraft
TellMeWhen
TullaRange
WeakAuras

That's it from my side. Hope it helps.

**Comment by Tuller** [comment]
I've added an additional forbidden frame check on that line as a hopeful workaround. Let me know if that helps for this one.

I suspect that the root cause is an addon, but I'm not 100% on this.
