### ISSUE TITLE
Cata Classic - 'CheckInteractDistance()' Action Blocked

### ISSUE THREAD

**Issue by evilgodly** [tullamods/OmniCC#436]
Getting this error randomly in Cata Classic on my Mage. Running OmniCC-10.2.9

22x [ADDON_ACTION_BLOCKED] AddOn 'OmniCD' tried to call the protected function 'CheckInteractDistance()'.
[string "@!BugGrabber/BugGrabber.lua"]:485: in function <!BugGrabber/BugGrabber.lua:485>
[string "=[C]"]: ?
[string "@OmniCD/Modules/Party/Inspect.lua"]:208: in function `RequestInspect'
[string "@OmniCD/Modules/Party/Inspect.lua"]:88: in function <OmniCD/Modules/Party/Inspect.lua:85>

Locals:
_ = Frame {
 RegisterEvent = <function> defined @!BugGrabber/BugGrabber.lua:491
 0 = <userdata>
 UnregisterEvent = <function> defined @!BugGrabber/BugGrabber.lua:491
 SetScript = <function> defined @!BugGrabber/BugGrabber.lua:491
}
event = "ADDON_ACTION_BLOCKED"
events = <table> {
 ADDON_ACTION_BLOCKED = <function> defined @!BugGrabber/BugGrabber.lua:557
 ADDON_ACTION_FORBIDDEN = <function> defined @!BugGrabber/BugGrabber.lua:557
 PLAYER_LOGIN = <function> defined @!BugGrabber/BugGrabber.lua:551
 LUA_WARNING = <function> defined @!BugGrabber/BugGrabber.lua:566
 ADDON_LOADED = <function> defined @!BugGrabber/BugGrabber.lua:511
}

**Comment by Tuller** [comment]
This error is from OmniCD not OmniCC

**Comment by evilgodly** [comment]
woops, will get that fixed.
