### ISSUE TITLE
Cooldowns hiding behind keybind text

### ISSUE THREAD

**Issue by Ahnzhael** [tullamods/OmniCC#439]
After 11.0 cooldowns on my actionbars are hiding behind the assinged keybind for the specific hotkey.. i use bartender and have tried to disable it but i still have the same issue.

I'll attach a screenshot to show what i mean.
![CDs](https://github.com/user-attachments/assets/98b37755-354d-4a01-bc30-67cd86c49e3d)

**Comment by Ahnzhael** [comment]
On my Shift-R keybind the cooldown is appearing behind the hotkey keybind. what can i do to fix this, as it was not like this for many many years

**Comment by Tuller** [comment]
Do you see this without masque?

**Comment by Ahnzhael** [comment]
hold up, when both masque and bartender is disabled it works like normal. so its gotta do with bartender im pretty sure

**Comment by Ahnzhael** [comment]
I can confirm it is bardtender that makes this happen. As to why i do not know. i have spent over 2 hours scouring through its options but there is nothing to do with the actua ltext overlay itself, hence why im asking here that maybe it COULD have something to do with Omni CC aswell. As i said it has never been this way and i have used this setup for arounf 7-8 years and the CD text has never been behind the keybind text...

**Comment by Ahnzhael** [comment]
I deleted my previous replies, as i did not look close enough, i have tried to disable ALL addons except omni cc (even deleted settings and reinstalled) and i still have the same issue with the cooldown numbers hiding behind the button keybind
PLEASE HELP ME

**Comment by Ahnzhael** [comment]
Asked blizzard and they said it could be a faulty installation, so i xompletely uninstalled everything, the game all addons, curseforge etc. re installed got bartender and omniCC, still the same issue............................

**Comment by Ahnzhael** [comment]
> I have the same issue even with zero addons installed except OmniCC. I found easy solution wich requires to modify original code:
> 
> https://github.com/tullamods/OmniCC/blob/9770d0f86edf7f749a39f0801d893bb18eb592d4/OmniCC/core/display.lua#L144
> 
> Change "7" to "500". It needs because hotkey frames have the same strata and their level equals 500.

You are my hero i needed and did not deserve it worked! i can not thank you enough :D

**Comment by Tuller** [comment]
This has been applied to 11.0.1, thanks!
