### ISSUE TITLE
An error is reported when you use the preview feature

### ISSUE THREAD

**Issue by Jock-SSH** [tullamods/OmniCC#440]
**Give us a clear and concise description of the problem, and what you expect to happen**

1）There is no setting option for OmniCC in Settings - Plugins；

2）After using the /oc command to open the settings screen, an error occurs after clicking the preview button.
![1](https://github.com/user-attachments/assets/646d0f22-fa78-46d1-aeb1-444dcfd0485b)

![image](https://github.com/user-attachments/assets/b4f767ab-59ba-463b-a8d3-5145d168878a)

**Do you have any steps to reproduce this issue?**

The error can be reproduced every time.
Prior to this feedback, I deleted all the contents of the "Interface" and "WTF" folders and reinstalled the plugin in the image below.

**Are you getting any error messages?**

”1x OmniCC_Config/preview.lua:14: attempt to call global 'GetSpellBookItemTexture' (a nil value)
[string "@OmniCC_Config/preview.lua"]:14: in function <OmniCC_Config/preview.lua:6>
[string "@OmniCC_Config/preview.lua"]:39: in function <OmniCC_Config/preview.lua:38>
[string "=[C]"]: in function `Show'
[string "@OmniCC_Config/preview.lua"]:127: in function `SetTheme'
[string "@OmniCC_Config/themes.lua"]:482: in function <OmniCC_Config/themes.lua:481>
[string "=[C]"]: ?
[string "@OmniCC_Config/libs/AceConfig-3.0-3/AceConfigDialog-3.0-86/AceConfigDialog-3.0.lua"]:45: in function <...nfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua:43>
[string "@OmniCC_Config/libs/AceConfig-3.0-3/AceConfigDialog-3.0-86/AceConfigDialog-3.0.lua"]:836: in function <...nfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua:658>
[string "=[C]"]: ?
[string "@OmniCC_Config/libs/AceGUI-3.0-41/AceGUI-3.0.lua"]:66: in function <OmniCC_Config/libs/AceGUI-3.0/AceGUI-3.0.lua:64>
[string "@OmniCC_Config/libs/AceGUI-3.0-41/AceGUI-3.0.lua"]:300: in function `Fire'
[string "@OmniCC_Config/libs/AceGUI-3.0-41/widgets/AceGUIWidget-Button.lua"]:22: in function <...nfig/libs/AceGUI-3.0/widgets/AceGUIWidget-Button.lua:19>

Locals:
icons = <table> {
}
(for index) = 1
(for limit) = 5
(for step) = 1
i = 1
offset = 0
numSpells = 14
tabEnd = 14
(for index) = 0
(for limit) = 13
(for step) = 1
j = 0
(*temporary) = nil
(*temporary) = 0
(*temporary) = "player"
(*temporary) = "attempt to call global 'GetSpellBookItemTexture' (a nil value)"
”.

**What version of OmniCC are you running?**

The latest version downloaded from curseforge is detailed in the image below.
![3](https://github.com/user-attachments/assets/ba09ae38-cfa3-4908-8728-e5b5b085139a)

**What version of World of Warcraft are you on?**

11.0.0.55824.

**What other addons are you running?**

The installed plug-ins are shown below.
![2](https://github.com/user-attachments/assets/1412d5a8-ac9b-4896-981c-598d30c9fb77)

**Comment by Tuller** [comment]
Resolved in 11.0.0

**Comment by Jock-SSH** [comment]
Thanks for the reply and the development work; this bug was perfectly resolved in the next update following my previous feedback.
