### ISSUE TITLE
Lastest update broke entirely on classic era

### ISSUE THREAD

**Issue by plzfix** [tullamods/OmniCC#450]
With the lastest update pushed on curseforge, the addon broke down and doesn't even show in the addon list anymore.

**Comment by Tuller** [comment]
What version of World of Warcraft are you running?

**Comment by tbrad86** [comment]
I can confirm it is currently broken in version WoW v1.15.4 (SoD). I had to downgrade to 11.0.1 for the addon to work.

**Comment by Tuller** [comment]
Can you do a clean install of the addon? I want to eliminate the possibility that you have some extra TOC files in your OmniCC directory. There should only be one with this version.

**Comment by tbrad86** [comment]
I can confirm everything seems to be working well again with 11.0.3. I had updated before I saw this message.

**Comment by KyleLuong227** [comment]
I am still having this issue with the latest version 11.0.3. I did move the OmniCC_Vanilla.toc over from version 11.0.1 and it works again if that helps.

**Comment by Drulludanni** [comment]
I'm having the same issue still, it has been going on for a while, I've tried to uninstall and reinstall but any version above 11.0.1 does not work (and it simply does not show up in the addon list).
