### ISSUE TITLE
Proc Effect Bug in 5.2.3

### ISSUE THREAD

**Issue by thomshouse** [tullamods/OmniCC#72]
With OmniCC updated to 5.2.3, the "proc" effect on my action bar buttons freaks out in size, placement, and opacity, and there's also a strange glowing box that sometimes appears on screen, seemingly anchored to my tooltip.  I am using a few other addons:
- Dominos
- Masque
- TipTac

...but OmniCC is the only addon that had updated in the time frame that these glitches started to occur.

 I reverted to 5.2.2 and the issues did go away.

**Comment by nitz** [comment]
Hi again. I know this is a wicked old ticket, but I just wanted to report: I'm still seeing the behavior on 6.2.3 :)

**Comment by nitz** [comment]
Just updating to report that I'm still experiencing this on 7.0.3. In fact, now the bizarre effect can get 'stuck' on the screen until the icon it's anchored to goes away. I wonder if perhaps it has something to do with #152. If I get a chance this week I'll see if I can narrow down what seems to be interacting with it the most.
