### ISSUE TITLE
Cannot use animation without showing the text

### ISSUE THREAD

**Issue by Adirelle** [tullamods/OmniCC#87]
Hello,

I'd like to display the countdown text only for long cooldowns 1 minute or more) but still have the finishing animation for shorter cooldowns.

Actually, if I set "Minimum duration to display text" to 1 minute, it also disables the finishing animation for cooldowns shorter than 1 minute.

Is there a solution to this ?

**Comment by Tuller** [comment]
If you set the opacity of each style to zero, then you'll end up with effects and no text.
