### ISSUE TITLE
Finish effect doesn't work on Raven

### ISSUE THREAD

**Issue by Stinkykiller** [tullamods/OmniCC#90]
Until today it was all ok but after i removed "Raven" and install "Aura frames" the problem show out. I try to bring back "Raven" and deleted all settings of all 3 addons but nothing changed. Now i'm stuck with this problem and i dont know where to start looking for a solution or even how to find one. On side note before on my shaman i got red sqare around my spell button (e.g. flame shock) and when debuff on my target is close to expire it was blinking - now even this option doesnt work anymore.
I'm not sure if all this was a result what "Omnicc" got from "Raven" or the problem could be something else.

**Comment by Tuller** [comment]
Raven hides the cooldown before we can actually trigger an effect off of it.
